"""
wave2b_recipes.py — Wave 2 part B (remaining 11 gen_* concepts).

Same quality bar as wave2a. Apply: python3 apply_wave.py wave2b_recipes.py [--apply]
"""

WAVE = [
    {
        "id": "gen_moroccan_chickpea_stew",
        "title": "Moroccan Chickpea & Sweet Potato Stew",
        "source": "claude_chat",
        "source_url": "https://www.acouplecooks.com/moroccan-chickpea-stew/",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 40,
        "prep_minutes": 15,
        "cook_minutes": 25,
        "cuisines": ["moroccan"],
        "diet_tags": ["vegetarian", "vegan", "gluten free"],
        "dish_types": ["main course"],
        "equipment": ["dutch_oven", "stovetop"],
        "proteins": ["plant"],
        "carbs": ["grain"],
        "regen_pending": False,
        "ingredients": [
            {"name": "sweet potatoes", "amount": 1.5, "unit": "lb", "aisle": "Produce",
             "group": "Stew", "original_text": "1.5 lb sweet potatoes, peeled, 3/4-inch dice"},
            {"name": "chickpeas", "amount": 30, "unit": "oz", "aisle": "Canned and Jarred",
             "group": "Stew", "original_text": "2 cans (15 oz each) chickpeas, drained and rinsed"},
            {"name": "yellow onion", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Stew", "original_text": "1 yellow onion, chopped"},
            {"name": "garlic", "amount": 3, "unit": "count", "aisle": "Produce",
             "group": "Stew", "original_text": "3 garlic cloves, minced"},
            {"name": "diced tomatoes", "amount": 14.5, "unit": "oz", "aisle": "Canned and Jarred",
             "group": "Stew", "original_text": "1 can (14.5 oz) diced tomatoes"},
            {"name": "vegetable broth", "amount": 3, "unit": "cup", "aisle": "Canned and Jarred",
             "group": "Stew", "original_text": "3 cups vegetable broth"},
            {"name": "olive oil", "amount": 2, "unit": "tbsp", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "Stew", "original_text": "2 tbsp olive oil"},
            {"name": "baby spinach", "amount": 3, "unit": "cup", "aisle": "Produce",
             "group": "Stew", "original_text": "3 cups baby spinach"},
            {"name": "ground cumin", "amount": 2, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Spice mix", "original_text": "2 tsp ground cumin"},
            {"name": "ground coriander", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Spice mix", "original_text": "1 tsp ground coriander"},
            {"name": "ground cinnamon", "amount": 0.5, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Spice mix", "original_text": "1/2 tsp cinnamon"},
            {"name": "sweet paprika", "amount": 2, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Spice mix", "original_text": "2 tsp sweet paprika"},
            {"name": "kosher salt", "amount": 1.25, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Spice mix", "original_text": "1.25 tsp kosher salt"},
            {"name": "couscous", "amount": 1.5, "unit": "cup", "aisle": "Pasta and Rice",
             "group": "For serving", "original_text": "1.5 cups couscous"},
            {"name": "sliced almonds", "amount": 0.33, "unit": "cup", "aisle": "Nuts",
             "group": "For serving", "original_text": "1/3 cup toasted sliced almonds (optional crunch)"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Heat 2 tbsp olive oil in a dutch oven over medium. Cook the onion 4-5 minutes until soft; add garlic and the spice mix (2 tsp cumin, 1 tsp coriander, 1/2 tsp cinnamon, 2 tsp paprika, 1.25 tsp salt), stir 30 seconds."},
            {"step_number": 2, "text": "Add sweet potatoes, chickpeas, tomatoes, and 3 cups broth. Bring to a boil, then simmer 20 minutes until the sweet potatoes are fork-tender."},
            {"step_number": 3, "text": "Mash a few sweet potato cubes against the pot wall to thicken the broth."},
            {"step_number": 4, "text": "Stir in the spinach until wilted, 1 minute. Taste — add salt or a squeeze of lemon if it tastes flat."},
            {"step_number": 5, "text": "Make the couscous: 1.5 cups couscous + 1.75 cups boiling water, cover 5 minutes, fluff."},
            {"step_number": 6, "text": "Serve the stew over couscous, topped with almonds."},
        ],
    },
    {
        "id": "gen_moroccan_lamb_couscous",
        "title": "Moroccan Ground Lamb & Couscous",
        "source": "claude_chat",
        "source_url": "",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 30,
        "prep_minutes": 10,
        "cook_minutes": 20,
        "cuisines": ["moroccan"],
        "diet_tags": [],
        "dish_types": ["main course"],
        "equipment": ["skillet", "stovetop"],
        "proteins": ["lamb"],
        "carbs": ["grain"],
        "regen_pending": False,
        "ingredients": [
            {"name": "ground lamb", "amount": 1.25, "unit": "lb", "aisle": "Meat",
             "group": "Lamb", "original_text": "1.25 lb ground lamb"},
            {"name": "yellow onion", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Lamb", "original_text": "1 yellow onion, chopped"},
            {"name": "garlic", "amount": 3, "unit": "count", "aisle": "Produce",
             "group": "Lamb", "original_text": "3 garlic cloves, minced"},
            {"name": "ground cumin", "amount": 2, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Lamb", "original_text": "2 tsp ground cumin"},
            {"name": "ground cinnamon", "amount": 0.5, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Lamb", "original_text": "1/2 tsp cinnamon"},
            {"name": "sweet paprika", "amount": 2, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Lamb", "original_text": "2 tsp sweet paprika"},
            {"name": "kosher salt", "amount": 1.25, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Lamb", "original_text": "1.25 tsp kosher salt + black pepper"},
            {"name": "dried apricots", "amount": 0.5, "unit": "cup", "aisle": "Dried Fruit",
             "group": "Lamb", "original_text": "1/2 cup dried apricots, chopped"},
            {"name": "chicken broth", "amount": 0.5, "unit": "cup", "aisle": "Canned and Jarred",
             "group": "Lamb", "original_text": "1/2 cup chicken broth"},
            {"name": "couscous", "amount": 1.5, "unit": "cup", "aisle": "Pasta and Rice",
             "group": "Couscous", "original_text": "1.5 cups couscous"},
            {"name": "frozen peas", "amount": 1, "unit": "cup", "aisle": "Frozen",
             "group": "Couscous", "original_text": "1 cup frozen peas (steamed into the couscous)"},
            {"name": "plain greek yogurt", "amount": 0.75, "unit": "cup", "aisle": "Dairy",
             "group": "For serving", "original_text": "3/4 cup plain Greek yogurt"},
            {"name": "fresh mint", "amount": 0.25, "unit": "cup", "aisle": "Produce",
             "group": "For serving", "original_text": "1/4 cup mint or parsley, chopped"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Brown the lamb in a dry large skillet over medium-high, breaking it up, 5-6 minutes. Lamb renders a lot — spoon off all but ~1 tbsp fat."},
            {"step_number": 2, "text": "Add the onion; cook 4 minutes until soft. Add garlic and the spices (2 tsp cumin, 1/2 tsp cinnamon, 2 tsp paprika, 1.25 tsp salt, pepper); stir 30 seconds."},
            {"step_number": 3, "text": "Add the chopped apricots and 1/2 cup broth; simmer 3-4 minutes until saucy, scraping up the browned bits."},
            {"step_number": 4, "text": "Meanwhile: 1.5 cups couscous + 1 cup frozen peas in a bowl, pour over 1.75 cups boiling water, cover 5 minutes, fluff."},
            {"step_number": 5, "text": "Taste the lamb — the apricots should read sweet-savory, not dessert; a squeeze of lemon balances it."},
            {"step_number": 6, "text": "Serve the lamb over the pea couscous with yogurt and mint. (The household's one lamb dish — ground only, occasional.)"},
        ],
    },
    {
        "id": "gen_moroccan_shrimp_chermoula",
        "title": "Shrimp Chermoula Skillet",
        "source": "claude_chat",
        "source_url": "",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 30,
        "prep_minutes": 15,
        "cook_minutes": 15,
        "cuisines": ["moroccan"],
        "diet_tags": ["gluten free"],
        "dish_types": ["main course"],
        "equipment": ["skillet", "stovetop"],
        "proteins": ["shrimp"],
        "carbs": ["grain"],
        "regen_pending": False,
        "ingredients": [
            {"name": "large shrimp", "amount": 1.5, "unit": "lb", "aisle": "Seafood",
             "group": "Shrimp", "original_text": "1.5 lb large shrimp, peeled and deveined"},
            {"name": "fresh cilantro", "amount": 1, "unit": "cup", "aisle": "Produce",
             "group": "Chermoula", "original_text": "1 cup cilantro leaves and stems"},
            {"name": "fresh parsley", "amount": 0.5, "unit": "cup", "aisle": "Produce",
             "group": "Chermoula", "original_text": "1/2 cup parsley"},
            {"name": "garlic", "amount": 3, "unit": "count", "aisle": "Produce",
             "group": "Chermoula", "original_text": "3 garlic cloves"},
            {"name": "ground cumin", "amount": 2, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Chermoula", "original_text": "2 tsp ground cumin"},
            {"name": "sweet paprika", "amount": 2, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Chermoula", "original_text": "2 tsp sweet paprika"},
            {"name": "lemon", "amount": 2, "unit": "count", "aisle": "Produce",
             "group": "Chermoula", "original_text": "2 lemons (1 juiced + zested, 1 in wedges)"},
            {"name": "olive oil", "amount": 0.33, "unit": "cup", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "Chermoula", "original_text": "1/3 cup olive oil"},
            {"name": "kosher salt", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Chermoula", "original_text": "1 tsp kosher salt"},
            {"name": "couscous", "amount": 1.5, "unit": "cup", "aisle": "Pasta and Rice",
             "group": "For serving", "original_text": "1.5 cups couscous"},
            {"name": "cherry tomatoes", "amount": 2, "unit": "cup", "aisle": "Produce",
             "group": "For serving", "original_text": "2 cups cherry tomatoes, halved"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Blitz the chermoula: cilantro, parsley, garlic, 2 tsp cumin, 2 tsp paprika, juice + zest of 1 lemon, 1/3 cup olive oil, 1 tsp salt. It should be a loose, vivid green sauce."},
            {"step_number": 2, "text": "Toss the shrimp with half the chermoula; marinate 10 minutes (no longer — the lemon starts cooking them)."},
            {"step_number": 3, "text": "Make the couscous: 1.5 cups couscous + 1.75 cups boiling water, cover 5 minutes, fluff with a fork."},
            {"step_number": 4, "text": "Heat a large skillet over medium-high until hot. Cook the shrimp in one layer, 2 minutes per side, until pink and curled into loose C-shapes."},
            {"step_number": 5, "text": "Off the heat, toss the shrimp with the cherry tomatoes and 2 more spoonfuls of chermoula."},
            {"step_number": 6, "text": "Serve over couscous with the remaining chermoula and lemon wedges. (Counts toward the 1-shrimp-per-month cadence.)"},
        ],
    },
    {
        "id": "gen_pesto_chicken_skillet",
        "title": "Pesto Chicken & Veggie Skillet",
        "source": "claude_chat",
        "source_url": "",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 30,
        "prep_minutes": 10,
        "cook_minutes": 20,
        "cuisines": ["italian"],
        "diet_tags": [],
        "dish_types": ["main course"],
        "equipment": ["skillet", "stovetop"],
        "proteins": ["chicken"],
        "carbs": ["pasta"],
        "regen_pending": False,
        "ingredients": [
            {"name": "boneless skinless chicken breasts", "amount": 1.5, "unit": "lb", "aisle": "Meat",
             "group": "Skillet", "original_text": "1.5 lb chicken breasts, cut into 1-inch pieces"},
            {"name": "basil pesto", "amount": 0.5, "unit": "cup", "aisle": "Canned and Jarred",
             "group": "Skillet", "original_text": "1/2 cup store-bought basil pesto (refrigerated section is noticeably better)"},
            {"name": "cherry tomatoes", "amount": 2, "unit": "cup", "aisle": "Produce",
             "group": "Skillet", "original_text": "2 cups cherry tomatoes"},
            {"name": "zucchini", "amount": 2, "unit": "count", "aisle": "Produce",
             "group": "Skillet", "original_text": "2 zucchini, half-moons"},
            {"name": "olive oil", "amount": 2, "unit": "tbsp", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "Skillet", "original_text": "2 tbsp olive oil"},
            {"name": "kosher salt", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Skillet", "original_text": "1 tsp kosher salt + black pepper"},
            {"name": "penne pasta", "amount": 12, "unit": "oz", "aisle": "Pasta and Rice",
             "group": "Pasta", "original_text": "12 oz penne or rotini"},
            {"name": "parmesan cheese", "amount": 0.5, "unit": "cup", "aisle": "Cheese",
             "group": "For serving", "original_text": "1/2 cup grated parmesan"},
            {"name": "fresh mozzarella pearls", "amount": 8, "unit": "oz", "aisle": "Cheese",
             "group": "For serving", "original_text": "8 oz mozzarella pearls (optional, kids love them)"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Boil salted water; cook the penne to al dente per the package. Reserve 1/2 cup pasta water before draining."},
            {"step_number": 2, "text": "Meanwhile, season the chicken with 1 tsp salt and pepper. Heat 1 tbsp olive oil in a large skillet over medium-high; cook the chicken 5-6 minutes, stirring once or twice, until golden and 165°F. Remove."},
            {"step_number": 3, "text": "Add the remaining 1 tbsp oil, then zucchini; cook 3 minutes. Add cherry tomatoes; cook 2-3 minutes more until the tomatoes just start to burst."},
            {"step_number": 4, "text": "Return the chicken with the drained pasta, 1/2 cup pesto, and a splash of pasta water. Toss off the heat — pesto goes army-green and dull if it boils."},
            {"step_number": 5, "text": "Loosen with more pasta water until glossy. Taste for salt."},
            {"step_number": 6, "text": "Serve with parmesan, and mozzarella pearls folded in at the table."},
        ],
    },
    {
        "id": "gen_pork_carnitas_tacos",
        "title": "Slow-Cooker Carnitas Tacos",
        "source": "claude_chat",
        "source_url": "https://www.recipetineats.com/pork-carnitas-mexican-slow-cooker-pulled-pork/",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 500,
        "prep_minutes": 20,
        "cook_minutes": 480,
        "cuisines": ["mexican"],
        "diet_tags": ["gluten free"],
        "dish_types": ["main course"],
        "equipment": ["slow_cooker", "sheet_pan"],
        "proteins": ["pork"],
        "carbs": ["bread"],
        "regen_pending": False,
        "ingredients": [
            {"name": "pork shoulder", "amount": 3, "unit": "lb", "aisle": "Meat",
             "group": "Carnitas", "original_text": "3 lb boneless pork shoulder (butt), cut into 4 chunks"},
            {"name": "orange", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Carnitas", "original_text": "1 orange, juiced (the RecipeTin signature)"},
            {"name": "yellow onion", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Carnitas", "original_text": "1 yellow onion, chopped"},
            {"name": "garlic", "amount": 4, "unit": "count", "aisle": "Produce",
             "group": "Carnitas", "original_text": "4 garlic cloves, minced"},
            {"name": "dried oregano", "amount": 1, "unit": "tbsp", "aisle": "Spices and Seasonings",
             "group": "Carnitas", "original_text": "1 tbsp dried oregano"},
            {"name": "ground cumin", "amount": 2, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Carnitas", "original_text": "2 tsp ground cumin"},
            {"name": "kosher salt", "amount": 1, "unit": "tbsp", "aisle": "Spices and Seasonings",
             "group": "Carnitas", "original_text": "1 tbsp kosher salt + 1 tsp black pepper"},
            {"name": "corn tortillas", "amount": 16, "unit": "count", "aisle": "Bakery",
             "group": "Tacos", "original_text": "16 small corn or flour tortillas, warmed"},
            {"name": "shredded cabbage", "amount": 2, "unit": "cup", "aisle": "Produce",
             "group": "Tacos", "original_text": "2 cups shredded cabbage or slaw mix"},
            {"name": "shredded monterey jack", "amount": 1.5, "unit": "cup", "aisle": "Cheese",
             "group": "Tacos", "original_text": "1.5 cups shredded cheese"},
            {"name": "salsa", "amount": 1, "unit": "cup", "aisle": "Canned and Jarred",
             "group": "Tacos", "original_text": "1 cup mild salsa"},
            {"name": "limes", "amount": 2, "unit": "count", "aisle": "Produce",
             "group": "Tacos", "original_text": "2 limes, in wedges"},
            {"name": "sour cream", "amount": 0.5, "unit": "cup", "aisle": "Dairy",
             "group": "Tacos", "original_text": "1/2 cup sour cream"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Rub the pork chunks all over with 1 tbsp salt, 1 tsp pepper, 1 tbsp oregano, and 2 tsp cumin."},
            {"step_number": 2, "text": "Place in the slow cooker with the onion, garlic, and orange juice. No added liquid — the pork makes its own."},
            {"step_number": 3, "text": "Cook on LOW 8-10 hours (or HIGH 5-6) until it shreds with no resistance."},
            {"step_number": 4, "text": "Shred the pork in the cooker with two forks; toss in the juices."},
            {"step_number": 5, "text": "Crisping (don't skip — this is what makes carnitas carnitas): spread the pork on a sheet pan, spoon some juices over, broil 5-8 minutes until the edges are browned and crackly. Toss once."},
            {"step_number": 6, "text": "Warm the tortillas (30 sec/side in a dry skillet or wrapped in foil in the oven)."},
            {"step_number": 7, "text": "Build-your-own taco night: pork, cabbage, cheese, salsa, sour cream, lime. Leftover pork freezes beautifully."},
        ],
    },
    {
        "id": "gen_pork_chops_sheet_pan",
        "title": "Sheet-Pan Garlic-Herb Pork Chops & Potatoes",
        "source": "claude_chat",
        "source_url": "",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 45,
        "prep_minutes": 15,
        "cook_minutes": 30,
        "cuisines": ["american"],
        "diet_tags": ["gluten free"],
        "dish_types": ["main course"],
        "equipment": ["oven", "sheet_pan"],
        "proteins": ["pork"],
        "carbs": ["potato"],
        "regen_pending": False,
        "ingredients": [
            {"name": "boneless pork chops", "amount": 4, "unit": "count", "aisle": "Meat",
             "group": "Pork chops", "original_text": "4 boneless pork chops, 1-inch thick (thin chops dry out — buy thick)"},
            {"name": "olive oil", "amount": 3, "unit": "tbsp", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "Garlic-herb rub", "original_text": "3 tbsp olive oil, divided"},
            {"name": "garlic", "amount": 4, "unit": "count", "aisle": "Produce",
             "group": "Garlic-herb rub", "original_text": "4 garlic cloves, minced"},
            {"name": "dried rosemary", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Garlic-herb rub", "original_text": "1 tsp dried rosemary (or 1 tbsp fresh)"},
            {"name": "dried thyme", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Garlic-herb rub", "original_text": "1 tsp dried thyme"},
            {"name": "dijon mustard", "amount": 1, "unit": "tbsp", "aisle": "Condiments",
             "group": "Garlic-herb rub", "original_text": "1 tbsp Dijon mustard"},
            {"name": "kosher salt", "amount": 1.5, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Garlic-herb rub", "original_text": "1.5 tsp kosher salt + black pepper"},
            {"name": "baby potatoes", "amount": 1.5, "unit": "lb", "aisle": "Produce",
             "group": "Vegetables", "original_text": "1.5 lb baby potatoes, halved"},
            {"name": "green beans", "amount": 1, "unit": "lb", "aisle": "Produce",
             "group": "Vegetables", "original_text": "1 lb green beans, trimmed"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Heat the oven to 425°F. Mix the rub: 2 tbsp olive oil, garlic, rosemary, thyme, Dijon, 1.5 tsp salt, pepper."},
            {"step_number": 2, "text": "Toss the halved potatoes with 1 tbsp oil and a pinch of salt; roast cut-side down on the sheet pan for a 15-minute head start (they take longer than the chops)."},
            {"step_number": 3, "text": "Coat the chops all over with the rub."},
            {"step_number": 4, "text": "Pull the pan, push the potatoes aside, add the chops and green beans. Roast 15-18 minutes until the chops read 140°F."},
            {"step_number": 5, "text": "Rest the chops 5 minutes on a cutting board (carryover takes them to 145°F — juicy, slightly blush). Potatoes back in the oven if they need more crisp."},
            {"step_number": 6, "text": "Slice the chops and serve with the pan juices spooned over."},
        ],
    },
    {
        "id": "gen_pork_tenderloin_slaw",
        "title": "Air-Fryer Pork Tenderloin with Apple Slaw",
        "source": "claude_chat",
        "source_url": "",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 35,
        "prep_minutes": 15,
        "cook_minutes": 20,
        "cuisines": ["american"],
        "diet_tags": ["gluten free"],
        "dish_types": ["main course"],
        "equipment": ["air_fryer"],
        "proteins": ["pork"],
        "carbs": ["potato"],
        "regen_pending": False,
        "ingredients": [
            {"name": "pork tenderloin", "amount": 1.5, "unit": "lb", "aisle": "Meat",
             "group": "Pork", "original_text": "1 pork tenderloin (about 1.5 lb), silverskin trimmed"},
            {"name": "smoked paprika", "amount": 2, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Pork", "original_text": "2 tsp smoked paprika"},
            {"name": "garlic powder", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Pork", "original_text": "1 tsp garlic powder"},
            {"name": "brown sugar", "amount": 1, "unit": "tbsp", "aisle": "Baking",
             "group": "Pork", "original_text": "1 tbsp brown sugar"},
            {"name": "kosher salt", "amount": 1.25, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Pork", "original_text": "1.25 tsp kosher salt + black pepper"},
            {"name": "olive oil", "amount": 1, "unit": "tbsp", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "Pork", "original_text": "1 tbsp olive oil"},
            {"name": "coleslaw mix", "amount": 14, "unit": "oz", "aisle": "Produce",
             "group": "Apple slaw", "original_text": "1 bag (14 oz) coleslaw mix"},
            {"name": "apple", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Apple slaw", "original_text": "1 crisp apple (Honeycrisp/Fuji), julienned"},
            {"name": "coleslaw dressing", "amount": 0.5, "unit": "cup", "aisle": "Condiments",
             "group": "Apple slaw", "original_text": "1/2 cup store-bought coleslaw dressing"},
            {"name": "apple cider vinegar", "amount": 1, "unit": "tbsp", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "Apple slaw", "original_text": "1 tbsp cider vinegar (sharpens the bottled dressing)"},
            {"name": "baby potatoes", "amount": 1.5, "unit": "lb", "aisle": "Produce",
             "group": "For serving", "original_text": "1.5 lb baby potatoes (microwave-steam, then smash with butter)"},
            {"name": "butter", "amount": 2, "unit": "tbsp", "aisle": "Dairy",
             "group": "For serving", "original_text": "2 tbsp butter, for the potatoes"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Mix the rub: 2 tsp smoked paprika, 1 tsp garlic powder, 1 tbsp brown sugar, 1.25 tsp salt, pepper. Rub the tenderloin with 1 tbsp oil, then the spice mix. Cut in half crosswise if it doesn't fit your basket."},
            {"step_number": 2, "text": "Air-fry at 400°F for 16-20 minutes, flipping halfway, until 140°F at the thickest point."},
            {"step_number": 3, "text": "Rest 5-10 minutes under foil (carryover to 145°F — pale pink center is correct and juicy, grey is overdone)."},
            {"step_number": 4, "text": "While it cooks: toss slaw mix and apple with the dressing and 1 tbsp vinegar. Refrigerate."},
            {"step_number": 5, "text": "Potatoes: microwave with 2 tbsp water, covered, 8-10 minutes until tender; smash lightly with butter and salt."},
            {"step_number": 6, "text": "Slice the pork into medallions; serve with slaw and potatoes, spooning any board juices over the meat."},
        ],
    },
    {
        "id": "gen_sausage_peppers_sheet_pan",
        "title": "Sheet-Pan Sausage, Peppers & Potatoes",
        "source": "claude_chat",
        "source_url": "",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 45,
        "prep_minutes": 10,
        "cook_minutes": 35,
        "cuisines": ["italian", "american"],
        "diet_tags": ["gluten free"],
        "dish_types": ["main course"],
        "equipment": ["oven", "sheet_pan"],
        "proteins": ["pork"],
        "carbs": ["potato"],
        "regen_pending": False,
        "ingredients": [
            {"name": "italian sausage links", "amount": 1.5, "unit": "lb", "aisle": "Meat",
             "group": "Sheet pan", "original_text": "1.5 lb sweet (mild) Italian sausage links"},
            {"name": "baby potatoes", "amount": 1.5, "unit": "lb", "aisle": "Produce",
             "group": "Sheet pan", "original_text": "1.5 lb baby potatoes, halved"},
            {"name": "bell peppers", "amount": 3, "unit": "count", "aisle": "Produce",
             "group": "Sheet pan", "original_text": "3 bell peppers (mixed colors), thick strips"},
            {"name": "red onion", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Sheet pan", "original_text": "1 red onion, wedges"},
            {"name": "olive oil", "amount": 3, "unit": "tbsp", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "Sheet pan", "original_text": "3 tbsp olive oil"},
            {"name": "italian seasoning", "amount": 2, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Sheet pan", "original_text": "2 tsp Italian seasoning"},
            {"name": "garlic powder", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Sheet pan", "original_text": "1 tsp garlic powder"},
            {"name": "kosher salt", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Sheet pan", "original_text": "1 tsp kosher salt + black pepper"},
            {"name": "crusty rolls", "amount": 4, "unit": "count", "aisle": "Bakery",
             "group": "For serving", "original_text": "4 crusty rolls (optional — sandwich night) or grainy mustard"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Heat the oven to 425°F. Toss the potatoes with 1 tbsp oil and a pinch of salt; roast cut-side down 15 minutes for a head start."},
            {"step_number": 2, "text": "Toss the peppers and onion with the remaining 2 tbsp oil, 2 tsp Italian seasoning, 1 tsp garlic powder, 1 tsp salt, pepper."},
            {"step_number": 3, "text": "Add the vegetables to the pan and nestle the whole sausage links among everything."},
            {"step_number": 4, "text": "Roast 25 minutes, turning the sausages and stirring the vegetables once, until the sausages read 160°F and are browned, and the potato edges are crisp."},
            {"step_number": 5, "text": "If the peppers need more char, broil 2-3 minutes."},
            {"step_number": 6, "text": "Slice the sausages on the bias and toss everything together with the pan juices. Serve as-is, or pile into rolls."},
        ],
    },
    {
        "id": "gen_viet_ginger_pork_bowls",
        "title": "Vietnamese Caramelized Ginger Pork Bowls",
        "source": "claude_chat",
        "source_url": "https://www.recipetineats.com/vietnamese-caramelised-pork-bowls/",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 25,
        "prep_minutes": 10,
        "cook_minutes": 15,
        "cuisines": ["vietnamese"],
        "diet_tags": [],
        "dish_types": ["main course"],
        "equipment": ["skillet", "stovetop"],
        "proteins": ["pork"],
        "carbs": ["rice"],
        "regen_pending": False,
        "ingredients": [
            {"name": "ground pork", "amount": 1.5, "unit": "lb", "aisle": "Meat",
             "group": "Pork", "original_text": "1.5 lb ground pork"},
            {"name": "fresh ginger", "amount": 2, "unit": "tbsp", "aisle": "Produce",
             "group": "Pork", "original_text": "2 tbsp fresh ginger, minced"},
            {"name": "garlic", "amount": 3, "unit": "count", "aisle": "Produce",
             "group": "Pork", "original_text": "3 garlic cloves, minced"},
            {"name": "shallot", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Pork", "original_text": "1 shallot (or 1/2 onion), finely chopped"},
            {"name": "brown sugar", "amount": 3, "unit": "tbsp", "aisle": "Baking",
             "group": "Caramel seasoning", "original_text": "3 tbsp brown sugar (this caramelizes — it's the dish)"},
            {"name": "fish sauce", "amount": 2.5, "unit": "tbsp", "aisle": "Ethnic Foods",
             "group": "Caramel seasoning", "original_text": "2.5 tbsp fish sauce"},
            {"name": "lime", "amount": 2, "unit": "count", "aisle": "Produce",
             "group": "Caramel seasoning", "original_text": "2 limes (1 juiced, 1 in wedges)"},
            {"name": "jasmine rice", "amount": 1.5, "unit": "cup", "aisle": "Pasta and Rice",
             "group": "Bowls", "original_text": "1.5 cups jasmine rice (uncooked)"},
            {"name": "cucumber", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Bowls", "original_text": "1 cucumber, thinly sliced"},
            {"name": "shredded carrots", "amount": 1, "unit": "cup", "aisle": "Produce",
             "group": "Bowls", "original_text": "1 cup shredded carrots"},
            {"name": "green onions", "amount": 3, "unit": "count", "aisle": "Produce",
             "group": "Bowls", "original_text": "3 green onions, sliced"},
            {"name": "fresh cilantro", "amount": 0.25, "unit": "cup", "aisle": "Produce",
             "group": "Bowls", "original_text": "1/4 cup cilantro leaves"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Start the rice (1.5 cups rice : 2.25 cups water, simmer covered 12 min, rest 10). Slice the cucumber and onions while it cooks."},
            {"step_number": 2, "text": "Heat a large skillet over high — no oil needed. Add the pork, ginger, garlic, and shallot; cook 4-5 minutes, breaking up, until the pork is no longer pink and the liquid has mostly evaporated."},
            {"step_number": 3, "text": "Sprinkle the 3 tbsp brown sugar over and add 2.5 tbsp fish sauce. Keep the heat HIGH."},
            {"step_number": 4, "text": "Cook 3-4 minutes, stirring only occasionally, until the juices reduce to a sticky glaze and bits of pork caramelize dark brown at the pan — those crispy edges are the whole point."},
            {"step_number": 5, "text": "Off heat, squeeze in the juice of 1 lime."},
            {"step_number": 6, "text": "Build bowls: rice, pork, cucumber, carrots, green onions, cilantro, lime wedge. Sweet-savory and very kid-friendly."},
        ],
    },
    {
        "id": "gen_viet_lemongrass_chicken",
        "title": "Vietnamese Lemongrass Chicken Stir-Fry",
        "source": "claude_chat",
        "source_url": "https://www.recipetineats.com/vietnamese-chicken-noodle-bowl/",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 35,
        "prep_minutes": 20,
        "cook_minutes": 15,
        "cuisines": ["vietnamese"],
        "diet_tags": [],
        "dish_types": ["main course"],
        "equipment": ["skillet", "stovetop"],
        "proteins": ["chicken"],
        "carbs": ["rice"],
        "regen_pending": False,
        "ingredients": [
            {"name": "boneless skinless chicken thighs", "amount": 1.75, "unit": "lb", "aisle": "Meat",
             "group": "Chicken & marinade", "original_text": "1.75 lb boneless skinless chicken thighs, bite-size pieces"},
            {"name": "lemongrass paste", "amount": 2, "unit": "tbsp", "aisle": "Produce",
             "group": "Chicken & marinade", "original_text": "2 tbsp lemongrass paste (tube, produce section) or 2 stalks, finely minced"},
            {"name": "fish sauce", "amount": 2, "unit": "tbsp", "aisle": "Ethnic Foods",
             "group": "Chicken & marinade", "original_text": "2 tbsp fish sauce"},
            {"name": "brown sugar", "amount": 2, "unit": "tbsp", "aisle": "Baking",
             "group": "Chicken & marinade", "original_text": "2 tbsp brown sugar"},
            {"name": "garlic", "amount": 3, "unit": "count", "aisle": "Produce",
             "group": "Chicken & marinade", "original_text": "3 garlic cloves, minced"},
            {"name": "soy sauce", "amount": 1, "unit": "tbsp", "aisle": "Ethnic Foods",
             "group": "Chicken & marinade", "original_text": "1 tbsp soy sauce"},
            {"name": "vegetable oil", "amount": 2, "unit": "tbsp", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "Stir-fry", "original_text": "2 tbsp vegetable oil"},
            {"name": "yellow onion", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Stir-fry", "original_text": "1 onion, sliced"},
            {"name": "green beans", "amount": 0.75, "unit": "lb", "aisle": "Produce",
             "group": "Stir-fry", "original_text": "3/4 lb green beans, cut in half"},
            {"name": "jasmine rice", "amount": 1.5, "unit": "cup", "aisle": "Pasta and Rice",
             "group": "For serving", "original_text": "1.5 cups jasmine rice (uncooked)"},
            {"name": "lime", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "For serving", "original_text": "1 lime, in wedges"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Marinate the chicken: lemongrass, 2 tbsp fish sauce, 2 tbsp brown sugar, garlic, 1 tbsp soy. 15 minutes minimum (or overnight)."},
            {"step_number": 2, "text": "Start the rice. Microwave the green beans with 2 tbsp water, covered, 2 minutes; drain."},
            {"step_number": 3, "text": "Heat 1 tbsp oil in a large skillet over HIGH. Add half the chicken in one layer; sear 2 minutes undisturbed, then stir-fry 2 minutes until caramelized at the edges and cooked through (165°F). Remove; repeat with remaining chicken."},
            {"step_number": 4, "text": "Add the last 1 tbsp oil; stir-fry the onion 2 minutes, then the green beans 1 minute."},
            {"step_number": 5, "text": "Return the chicken and any juices; toss 1 minute. The sugar in the marinade glazes everything — let it catch slightly on the pan."},
            {"step_number": 6, "text": "Serve over rice with lime wedges."},
        ],
    },
    {
        "id": "gen_viet_shaking_beef",
        "title": "Vietnamese Shaking Beef (Bò Lúc Lắc)",
        "source": "claude_chat",
        "source_url": "https://www.wenthere8this.com/bo-luc-lac/",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 30,
        "prep_minutes": 15,
        "cook_minutes": 15,
        "cuisines": ["vietnamese"],
        "diet_tags": [],
        "dish_types": ["main course"],
        "equipment": ["wok", "skillet", "stovetop"],
        "proteins": ["beef"],
        "carbs": ["rice"],
        "regen_pending": False,
        "ingredients": [
            {"name": "sirloin steak", "amount": 1.5, "unit": "lb", "aisle": "Meat",
             "group": "Beef & marinade", "original_text": "1.5 lb sirloin or tri-tip, 1-inch cubes"},
            {"name": "soy sauce", "amount": 2, "unit": "tbsp", "aisle": "Ethnic Foods",
             "group": "Beef & marinade", "original_text": "2 tbsp soy sauce"},
            {"name": "oyster sauce", "amount": 1.5, "unit": "tbsp", "aisle": "Ethnic Foods",
             "group": "Beef & marinade", "original_text": "1.5 tbsp oyster sauce"},
            {"name": "fish sauce", "amount": 1, "unit": "tbsp", "aisle": "Ethnic Foods",
             "group": "Beef & marinade", "original_text": "1 tbsp fish sauce"},
            {"name": "sugar", "amount": 2, "unit": "tsp", "aisle": "Baking",
             "group": "Beef & marinade", "original_text": "2 tsp sugar"},
            {"name": "garlic", "amount": 4, "unit": "count", "aisle": "Produce",
             "group": "Beef & marinade", "original_text": "4 garlic cloves, minced"},
            {"name": "vegetable oil", "amount": 2, "unit": "tbsp", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "Stir-fry", "original_text": "2 tbsp vegetable oil"},
            {"name": "red onion", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Stir-fry", "original_text": "1 red onion, thick slices"},
            {"name": "butter", "amount": 1, "unit": "tbsp", "aisle": "Dairy",
             "group": "Stir-fry", "original_text": "1 tbsp butter (the glossy finish)"},
            {"name": "watercress", "amount": 4, "unit": "cup", "aisle": "Produce",
             "group": "Salad bed", "original_text": "4 cups watercress or baby arugula"},
            {"name": "cherry tomatoes", "amount": 2, "unit": "cup", "aisle": "Produce",
             "group": "Salad bed", "original_text": "2 cups cherry tomatoes, halved"},
            {"name": "lime", "amount": 2, "unit": "count", "aisle": "Produce",
             "group": "Salad bed", "original_text": "2 limes — 1 juiced with salt & pepper for dipping, 1 in wedges"},
            {"name": "jasmine rice", "amount": 1.5, "unit": "cup", "aisle": "Pasta and Rice",
             "group": "For serving", "original_text": "1.5 cups jasmine rice (uncooked)"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Marinate the beef cubes: 2 tbsp soy, 1.5 tbsp oyster sauce, 1 tbsp fish sauce, 2 tsp sugar, garlic. 15 minutes while the rice cooks."},
            {"step_number": 2, "text": "Start the rice. Make the dipping sauce: juice of 1 lime + 1/2 tsp salt + plenty of black pepper."},
            {"step_number": 3, "text": "Arrange the watercress and tomatoes on a platter."},
            {"step_number": 4, "text": "Heat 2 tbsp oil in a wok over the HIGHEST heat until smoking. Add the beef in one layer; don't touch for 60-90 seconds to get a hard sear."},
            {"step_number": 5, "text": "Now shake — toss the pan (or stir hard) 1 minute, add the onion, shake 1-2 minutes more. Beef should be browned outside, medium within."},
            {"step_number": 6, "text": "Off heat, swirl in 1 tbsp butter until glossy."},
            {"step_number": 7, "text": "Pour the beef and onions over the salad bed — the juices wilt it into the dressing. Serve with rice and the lime-pepper dip."},
        ],
    },
]
