"""
wave4b_recipes.py — Wave 4 part B: new user-selected recipes (Mexican 5,
Korean 3, Thai 4 = 12). All NEW ids, enter unproven. Same schema/quality
bar. Mild as written (kids); chili crisp / sriracha at the table for adults.

Apply: python3 apply_wave.py wave4b_recipes.py [--apply]
"""

WAVE = [
    # ---------------- MEXICAN ----------------
    {
        "id": "gen_beef_barbacoa_bowls",
        "title": "Beef Barbacoa Bowls",
        "source": "claude_chat",
        "source_url": "https://www.recipetineats.com/beef-barbacoa/",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 500,
        "prep_minutes": 20,
        "cook_minutes": 480,
        "cuisines": ["mexican"],
        "diet_tags": ["gluten free"],
        "dish_types": ["main course"],
        "equipment": ["slow_cooker"],
        "proteins": ["beef"],
        "carbs": ["rice"],
        "ingredients": [
            {"name": "beef chuck roast", "amount": 2.5, "unit": "lb", "aisle": "Meat",
             "group": "Barbacoa", "original_text": "2.5 lb beef chuck roast, cut into 4 chunks"},
            {"name": "beef broth", "amount": 1, "unit": "cup", "aisle": "Canned and Jarred",
             "group": "Barbacoa", "original_text": "1 cup beef broth"},
            {"name": "diced green chiles", "amount": 4, "unit": "oz", "aisle": "Canned and Jarred",
             "group": "Barbacoa", "original_text": "1 can (4 oz) mild diced green chiles"},
            {"name": "lime", "amount": 2, "unit": "count", "aisle": "Produce",
             "group": "Barbacoa", "original_text": "2 limes, juiced"},
            {"name": "garlic", "amount": 4, "unit": "count", "aisle": "Produce",
             "group": "Barbacoa", "original_text": "4 garlic cloves, minced"},
            {"name": "ground cumin", "amount": 1, "unit": "tbsp", "aisle": "Spices and Seasonings",
             "group": "Spice mix", "original_text": "1 tbsp ground cumin"},
            {"name": "dried oregano", "amount": 2, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Spice mix", "original_text": "2 tsp dried oregano"},
            {"name": "smoked paprika", "amount": 2, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Spice mix", "original_text": "2 tsp smoked paprika"},
            {"name": "kosher salt", "amount": 2, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Spice mix", "original_text": "2 tsp kosher salt + black pepper"},
            {"name": "jasmine rice", "amount": 1.5, "unit": "cup", "aisle": "Pasta and Rice",
             "group": "Bowls", "original_text": "1.5 cups rice (uncooked), cooked with lime + cilantro"},
            {"name": "black beans", "amount": 15, "unit": "oz", "aisle": "Canned and Jarred",
             "group": "Bowls", "original_text": "1 can (15 oz) black beans, warmed"},
            {"name": "shredded monterey jack", "amount": 1, "unit": "cup", "aisle": "Cheese",
             "group": "Bowls", "original_text": "1 cup shredded cheese"},
            {"name": "sour cream", "amount": 0.5, "unit": "cup", "aisle": "Dairy",
             "group": "Bowls", "original_text": "1/2 cup sour cream + pico de gallo"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Rub the beef chunks with the spice mix: 1 tbsp cumin, 2 tsp oregano, 2 tsp paprika, 2 tsp salt, pepper."},
            {"step_number": 2, "text": "Put in the slow cooker with the broth, green chiles, lime juice, and garlic."},
            {"step_number": 3, "text": "Cook on LOW 8-9 hours (or HIGH 5-6) until the beef shreds with no resistance."},
            {"step_number": 4, "text": "Shred with two forks and toss in the juices; leave the lid off 10 minutes if it's soupy."},
            {"step_number": 5, "text": "Cook the rice; stir in lime juice and chopped cilantro for cilantro-lime rice."},
            {"step_number": 6, "text": "Build bowls: rice, black beans, barbacoa, cheese, sour cream, pico. Leftover beef freezes well for quesadillas."},
        ],
    },
    {
        "id": "gen_picadillo",
        "title": "Mexican Picadillo",
        "source": "claude_chat",
        "source_url": "https://www.mylatinatable.com/authentic-mexican-picadillo-recipe/",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 35,
        "prep_minutes": 15,
        "cook_minutes": 20,
        "cuisines": ["mexican"],
        "diet_tags": ["gluten free"],
        "dish_types": ["main course"],
        "equipment": ["skillet", "stovetop"],
        "proteins": ["beef"],
        "carbs": ["rice"],
        "ingredients": [
            {"name": "ground beef", "amount": 1.5, "unit": "lb", "aisle": "Meat",
             "group": "Picadillo", "original_text": "1.5 lb ground beef"},
            {"name": "yukon gold potatoes", "amount": 2, "unit": "count", "aisle": "Produce",
             "group": "Picadillo", "original_text": "2 potatoes, 1/2-inch dice"},
            {"name": "carrots", "amount": 2, "unit": "count", "aisle": "Produce",
             "group": "Picadillo", "original_text": "2 carrots, diced"},
            {"name": "yellow onion", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Picadillo", "original_text": "1 onion, chopped"},
            {"name": "garlic", "amount": 3, "unit": "count", "aisle": "Produce",
             "group": "Picadillo", "original_text": "3 garlic cloves, minced"},
            {"name": "tomato sauce", "amount": 15, "unit": "oz", "aisle": "Canned and Jarred",
             "group": "Picadillo", "original_text": "1 can (15 oz) tomato sauce"},
            {"name": "beef broth", "amount": 0.5, "unit": "cup", "aisle": "Canned and Jarred",
             "group": "Picadillo", "original_text": "1/2 cup beef broth"},
            {"name": "frozen peas", "amount": 1, "unit": "cup", "aisle": "Frozen",
             "group": "Picadillo", "original_text": "1 cup frozen peas"},
            {"name": "ground cumin", "amount": 2, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Spices", "original_text": "2 tsp ground cumin"},
            {"name": "dried oregano", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Spices", "original_text": "1 tsp oregano"},
            {"name": "ground cinnamon", "amount": 0.25, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Spices", "original_text": "1/4 tsp cinnamon (the secret warmth)"},
            {"name": "kosher salt", "amount": 1.25, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Spices", "original_text": "1.25 tsp kosher salt"},
            {"name": "jasmine rice", "amount": 1.5, "unit": "cup", "aisle": "Pasta and Rice",
             "group": "For serving", "original_text": "1.5 cups rice (uncooked)"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Start the rice. Brown the beef with the onion in a large skillet over medium-high, 5-6 minutes; spoon off excess fat."},
            {"step_number": 2, "text": "Add garlic and the spices (2 tsp cumin, 1 tsp oregano, 1/4 tsp cinnamon, 1.25 tsp salt); stir 1 minute."},
            {"step_number": 3, "text": "Add the diced potatoes and carrots, tomato sauce, and 1/2 cup broth. Stir to combine."},
            {"step_number": 4, "text": "Cover and simmer 12-15 minutes, stirring occasionally, until the potatoes are fork-tender."},
            {"step_number": 5, "text": "Stir in the peas; cook 3 minutes more. Taste for salt — it should be cozy and gently spiced, not hot."},
            {"step_number": 6, "text": "Serve over rice. Picadillo is even better next day, and fills tacos or empanadas."},
        ],
    },
    {
        "id": "gen_carne_asada_bowls",
        "title": "Carne Asada Bowls",
        "source": "claude_chat",
        "source_url": "https://www.recipetineats.com/carne-asada/",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 40,
        "prep_minutes": 25,
        "cook_minutes": 15,
        "cuisines": ["mexican"],
        "diet_tags": ["gluten free"],
        "dish_types": ["main course"],
        "equipment": ["grill", "skillet"],
        "proteins": ["beef"],
        "carbs": ["rice"],
        "ingredients": [
            {"name": "flank steak", "amount": 1.5, "unit": "lb", "aisle": "Meat",
             "group": "Carne asada", "original_text": "1.5 lb flank or skirt steak"},
            {"name": "lime", "amount": 3, "unit": "count", "aisle": "Produce",
             "group": "Marinade", "original_text": "3 limes (2 juiced into the marinade, 1 in wedges)"},
            {"name": "orange", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Marinade", "original_text": "1 orange, juiced"},
            {"name": "garlic", "amount": 4, "unit": "count", "aisle": "Produce",
             "group": "Marinade", "original_text": "4 garlic cloves, minced"},
            {"name": "fresh cilantro", "amount": 0.5, "unit": "cup", "aisle": "Produce",
             "group": "Marinade", "original_text": "1/2 cup cilantro, chopped (divided with the bowls)"},
            {"name": "ground cumin", "amount": 2, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Marinade", "original_text": "2 tsp ground cumin"},
            {"name": "olive oil", "amount": 3, "unit": "tbsp", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "Marinade", "original_text": "3 tbsp olive oil"},
            {"name": "kosher salt", "amount": 1.5, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Marinade", "original_text": "1.5 tsp kosher salt + black pepper"},
            {"name": "jasmine rice", "amount": 1.5, "unit": "cup", "aisle": "Pasta and Rice",
             "group": "Bowls", "original_text": "1.5 cups rice (uncooked), cilantro-lime"},
            {"name": "black beans", "amount": 15, "unit": "oz", "aisle": "Canned and Jarred",
             "group": "Bowls", "original_text": "1 can (15 oz) black beans, warmed"},
            {"name": "avocado", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Bowls", "original_text": "1 avocado, sliced"},
            {"name": "cherry tomatoes", "amount": 1.5, "unit": "cup", "aisle": "Produce",
             "group": "Bowls", "original_text": "1.5 cups cherry tomatoes, halved (quick pico)"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Marinate the steak: juice of 2 limes + the orange, garlic, half the cilantro, 2 tsp cumin, 3 tbsp oil, 1.5 tsp salt, pepper. 20 minutes (up to 4 hours — not longer, the citrus over-cures it)."},
            {"step_number": 2, "text": "Cook the rice; stir in lime juice and the rest of the cilantro."},
            {"step_number": 3, "text": "Heat the grill or a heavy skillet to HIGH until nearly smoking. Cook the steak 3-4 minutes per side for medium (130°F) — a hot, fast sear is everything here."},
            {"step_number": 4, "text": "Rest the steak 8-10 minutes on a board (don't skip — resting keeps the juices in), then slice THIN against the grain."},
            {"step_number": 5, "text": "Quick pico: toss the tomatoes with a pinch of salt and a squeeze of lime."},
            {"step_number": 6, "text": "Build bowls: cilantro-lime rice, black beans, sliced steak, avocado, pico, lime wedge."},
        ],
    },
    {
        "id": "gen_chicken_tinga_tacos",
        "title": "Chicken Tinga Tacos",
        "source": "claude_chat",
        "source_url": "https://www.recipetineats.com/chicken-tinga-tacos/",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 35,
        "prep_minutes": 10,
        "cook_minutes": 25,
        "cuisines": ["mexican"],
        "diet_tags": ["gluten free"],
        "dish_types": ["main course"],
        "equipment": ["skillet", "stovetop"],
        "proteins": ["chicken"],
        "carbs": ["bread"],
        "ingredients": [
            {"name": "boneless skinless chicken thighs", "amount": 1.75, "unit": "lb", "aisle": "Meat",
             "group": "Tinga", "original_text": "1.75 lb chicken thighs"},
            {"name": "fire-roasted diced tomatoes", "amount": 14.5, "unit": "oz", "aisle": "Canned and Jarred",
             "group": "Tinga sauce", "original_text": "1 can (14.5 oz) fire-roasted diced tomatoes"},
            {"name": "chipotle in adobo", "amount": 1, "unit": "count", "aisle": "Canned and Jarred",
             "group": "Tinga sauce", "original_text": "1 chipotle pepper from a can of adobo (mild kick — use 1, not the whole can; or 1 tsp adobo sauce only for no heat)"},
            {"name": "yellow onion", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Tinga sauce", "original_text": "1 onion, sliced"},
            {"name": "garlic", "amount": 3, "unit": "count", "aisle": "Produce",
             "group": "Tinga sauce", "original_text": "3 garlic cloves"},
            {"name": "ground cumin", "amount": 1.5, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Tinga sauce", "original_text": "1.5 tsp ground cumin"},
            {"name": "dried oregano", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Tinga sauce", "original_text": "1 tsp oregano"},
            {"name": "chicken broth", "amount": 0.5, "unit": "cup", "aisle": "Canned and Jarred",
             "group": "Tinga sauce", "original_text": "1/2 cup chicken broth"},
            {"name": "olive oil", "amount": 1, "unit": "tbsp", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "Tinga sauce", "original_text": "1 tbsp olive oil"},
            {"name": "kosher salt", "amount": 1.25, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Tinga sauce", "original_text": "1.25 tsp kosher salt"},
            {"name": "corn tortillas", "amount": 8, "unit": "count", "aisle": "Bakery",
             "group": "Tacos", "original_text": "8 corn tortillas, warmed"},
            {"name": "cotija cheese", "amount": 0.5, "unit": "cup", "aisle": "Cheese",
             "group": "Tacos", "original_text": "1/2 cup cotija or feta, + diced onion, cilantro, lime"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Heat 1 tbsp oil in a skillet over medium-high. Brown the chicken thighs 2-3 minutes per side; remove (they finish in the sauce)."},
            {"step_number": 2, "text": "Blend the tomatoes, chipotle, raw garlic, 1.5 tsp cumin, 1 tsp oregano, 1/2 cup broth, and 1.25 tsp salt until smooth."},
            {"step_number": 3, "text": "Cook the sliced onion in the same skillet 4 minutes, then pour in the blended sauce; simmer 3 minutes to deepen the color."},
            {"step_number": 4, "text": "Return the chicken; cover and simmer 12-15 minutes until it shreds easily and reads 175°F."},
            {"step_number": 5, "text": "Shred the chicken right in the sauce with two forks; toss to coat. It should be saucy but not soupy."},
            {"step_number": 6, "text": "Pile onto warm tortillas with cotija, onion, cilantro, and lime. (One chipotle = gentle warmth; leave it out entirely for the youngest.)"},
        ],
    },
    {
        "id": "gen_street_corn_chicken_bowls",
        "title": "Street Corn Chicken Rice Bowls",
        "source": "claude_chat",
        "source_url": "https://tastesbetterfromscratch.com/street-corn-chicken-rice-bowls/",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 35,
        "prep_minutes": 15,
        "cook_minutes": 20,
        "cuisines": ["mexican"],
        "diet_tags": ["gluten free"],
        "dish_types": ["main course"],
        "equipment": ["skillet", "stovetop"],
        "proteins": ["chicken"],
        "carbs": ["rice"],
        "ingredients": [
            {"name": "boneless skinless chicken thighs", "amount": 1.5, "unit": "lb", "aisle": "Meat",
             "group": "Chicken", "original_text": "1.5 lb chicken thighs"},
            {"name": "chili powder", "amount": 1, "unit": "tbsp", "aisle": "Spices and Seasonings",
             "group": "Chicken", "original_text": "1 tbsp mild chili powder + 1 tsp cumin"},
            {"name": "lime", "amount": 2, "unit": "count", "aisle": "Produce",
             "group": "Chicken", "original_text": "2 limes (1 for the chicken, 1 for the corn + bowls)"},
            {"name": "olive oil", "amount": 2, "unit": "tbsp", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "Chicken", "original_text": "2 tbsp olive oil"},
            {"name": "corn", "amount": 3, "unit": "cup", "aisle": "Frozen",
             "group": "Street corn", "original_text": "3 cups corn (frozen or fresh)"},
            {"name": "mayonnaise", "amount": 0.33, "unit": "cup", "aisle": "Condiments",
             "group": "Street corn", "original_text": "1/3 cup mayonnaise"},
            {"name": "cotija cheese", "amount": 0.5, "unit": "cup", "aisle": "Cheese",
             "group": "Street corn", "original_text": "1/2 cup cotija (or feta), crumbled"},
            {"name": "smoked paprika", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Street corn", "original_text": "1 tsp smoked paprika"},
            {"name": "fresh cilantro", "amount": 0.33, "unit": "cup", "aisle": "Produce",
             "group": "Street corn", "original_text": "1/3 cup cilantro, chopped"},
            {"name": "jasmine rice", "amount": 1.5, "unit": "cup", "aisle": "Pasta and Rice",
             "group": "Bowls", "original_text": "1.5 cups rice (uncooked)"},
            {"name": "kosher salt", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Bowls", "original_text": "1 tsp kosher salt"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Start the rice. Toss the chicken with 1 tbsp chili powder, 1 tsp cumin, the juice of 1 lime, 1 tbsp oil, 1 tsp salt."},
            {"step_number": 2, "text": "Heat 1 tbsp oil in a skillet over medium-high. Cook the chicken 5-6 minutes per side until charred at the edges and 175°F. Rest, then dice."},
            {"step_number": 3, "text": "In the same pan, char the corn over high heat 4-5 minutes, stirring little, until spots blacken — that char is the street-corn flavor."},
            {"step_number": 4, "text": "Off the heat, stir the corn with the mayo, half the cotija, 1 tsp paprika, half the cilantro, and a squeeze of lime."},
            {"step_number": 5, "text": "Build bowls: rice, chicken, a big scoop of street corn."},
            {"step_number": 6, "text": "Finish with the rest of the cotija, cilantro, and a lime wedge."},
        ],
    },
    # ---------------- KOREAN ----------------
    {
        "id": "gen_chicken_bulgogi",
        "title": "Chicken Bulgogi (Dak Bulgogi)",
        "source": "claude_chat",
        "source_url": "https://www.davidlebovitz.com/chicken-bulgogi-dak-korean-recipe/",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 35,
        "prep_minutes": 20,
        "cook_minutes": 15,
        "cuisines": ["korean"],
        "diet_tags": [],
        "dish_types": ["main course"],
        "equipment": ["skillet", "grill", "stovetop"],
        "proteins": ["chicken"],
        "carbs": ["rice"],
        "ingredients": [
            {"name": "boneless skinless chicken thighs", "amount": 1.75, "unit": "lb", "aisle": "Meat",
             "group": "Chicken & marinade", "original_text": "1.75 lb chicken thighs, thin bite-size pieces"},
            {"name": "low-sodium soy sauce", "amount": 0.25, "unit": "cup", "aisle": "Ethnic Foods",
             "group": "Chicken & marinade", "original_text": "1/4 cup low-sodium soy sauce"},
            {"name": "asian pear", "amount": 0.5, "unit": "count", "aisle": "Produce",
             "group": "Chicken & marinade", "original_text": "1/2 Asian pear (or regular pear), grated — the classic tenderizer"},
            {"name": "brown sugar", "amount": 2, "unit": "tbsp", "aisle": "Baking",
             "group": "Chicken & marinade", "original_text": "2 tbsp brown sugar"},
            {"name": "garlic", "amount": 4, "unit": "count", "aisle": "Produce",
             "group": "Chicken & marinade", "original_text": "4 garlic cloves, minced"},
            {"name": "fresh ginger", "amount": 1, "unit": "tbsp", "aisle": "Produce",
             "group": "Chicken & marinade", "original_text": "1 tbsp fresh ginger, minced"},
            {"name": "sesame oil", "amount": 1, "unit": "tbsp", "aisle": "Ethnic Foods",
             "group": "Chicken & marinade", "original_text": "1 tbsp toasted sesame oil"},
            {"name": "vegetable oil", "amount": 1, "unit": "tbsp", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "Cook", "original_text": "1 tbsp vegetable oil"},
            {"name": "yellow onion", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Cook", "original_text": "1 onion, sliced"},
            {"name": "green onions", "amount": 3, "unit": "count", "aisle": "Produce",
             "group": "Cook", "original_text": "3 green onions, cut into 1-inch lengths"},
            {"name": "jasmine rice", "amount": 1.5, "unit": "cup", "aisle": "Pasta and Rice",
             "group": "For serving", "original_text": "1.5 cups rice (uncooked)"},
            {"name": "sesame seeds", "amount": 1, "unit": "tbsp", "aisle": "Spices and Seasonings",
             "group": "For serving", "original_text": "1 tbsp sesame seeds"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Marinate the chicken: 1/4 cup soy, grated pear, 2 tbsp brown sugar, garlic, ginger, 1 tbsp sesame oil. 20 minutes (or overnight). Start the rice."},
            {"step_number": 2, "text": "Heat 1 tbsp vegetable oil in a large skillet over HIGH. Lift the chicken from the marinade (reserve it) and add in one layer; sear 2 minutes undisturbed."},
            {"step_number": 3, "text": "Add the onion and stir-fry 3-4 minutes until the chicken is caramelized and cooked through (165°F)."},
            {"step_number": 4, "text": "Pour in the reserved marinade; bubble 1-2 minutes until it reduces to a glossy glaze (cooking the raw marinade is important)."},
            {"step_number": 5, "text": "Toss in the green onions for the last 30 seconds."},
            {"step_number": 6, "text": "Serve over rice with sesame seeds. Sweet-savory and zero heat — a reliable kid win."},
        ],
    },
    {
        "id": "gen_japchae",
        "title": "Japchae (Korean Glass Noodle Stir-Fry)",
        "source": "claude_chat",
        "source_url": "",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 40,
        "prep_minutes": 25,
        "cook_minutes": 15,
        "cuisines": ["korean"],
        "diet_tags": [],
        "dish_types": ["main course"],
        "equipment": ["skillet", "stovetop"],
        "proteins": ["beef"],
        "carbs": ["pasta"],
        "ingredients": [
            {"name": "korean sweet potato glass noodles", "amount": 8, "unit": "oz", "aisle": "Ethnic Foods",
             "group": "Noodles", "original_text": "8 oz dangmyeon (sweet potato glass noodles)"},
            {"name": "sirloin steak", "amount": 0.75, "unit": "lb", "aisle": "Meat",
             "group": "Stir-fry", "original_text": "3/4 lb sirloin, thin strips"},
            {"name": "spinach", "amount": 4, "unit": "cup", "aisle": "Produce",
             "group": "Stir-fry", "original_text": "4 cups spinach"},
            {"name": "carrots", "amount": 2, "unit": "count", "aisle": "Produce",
             "group": "Stir-fry", "original_text": "2 carrots, julienned"},
            {"name": "red bell pepper", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Stir-fry", "original_text": "1 red bell pepper, thin strips"},
            {"name": "shiitake mushrooms", "amount": 4, "unit": "oz", "aisle": "Produce",
             "group": "Stir-fry", "original_text": "4 oz shiitake or cremini mushrooms, sliced"},
            {"name": "yellow onion", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Stir-fry", "original_text": "1 onion, sliced"},
            {"name": "low-sodium soy sauce", "amount": 5, "unit": "tbsp", "aisle": "Ethnic Foods",
             "group": "Sauce", "original_text": "5 tbsp low-sodium soy sauce"},
            {"name": "brown sugar", "amount": 2, "unit": "tbsp", "aisle": "Baking",
             "group": "Sauce", "original_text": "2 tbsp brown sugar"},
            {"name": "sesame oil", "amount": 2, "unit": "tbsp", "aisle": "Ethnic Foods",
             "group": "Sauce", "original_text": "2 tbsp toasted sesame oil"},
            {"name": "garlic", "amount": 3, "unit": "count", "aisle": "Produce",
             "group": "Sauce", "original_text": "3 garlic cloves, minced"},
            {"name": "vegetable oil", "amount": 2, "unit": "tbsp", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "Cook", "original_text": "2 tbsp vegetable oil"},
            {"name": "sesame seeds", "amount": 1, "unit": "tbsp", "aisle": "Spices and Seasonings",
             "group": "Cook", "original_text": "1 tbsp sesame seeds"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Boil the glass noodles 6-7 minutes until clear and chewy; drain, rinse, and snip a few times with scissors. Toss with 1 tbsp of the sesame oil so they don't clump."},
            {"step_number": 2, "text": "Mix the sauce: 5 tbsp soy, 2 tbsp brown sugar, the remaining 1 tbsp sesame oil, garlic."},
            {"step_number": 3, "text": "Wilt the spinach in a dry hot pan 1 minute; squeeze dry and set aside. This keeps it from watering out the dish."},
            {"step_number": 4, "text": "Heat 1 tbsp vegetable oil over high; stir-fry the beef 2-3 minutes until browned; remove. Add the last 1 tbsp oil and stir-fry onion, carrots, pepper, and mushrooms 3-4 minutes until crisp-tender."},
            {"step_number": 5, "text": "Add the noodles, beef, spinach, and sauce to the pan. Toss 2 minutes over medium until everything is glossy and the noodles have drunk up the sauce."},
            {"step_number": 6, "text": "Finish with sesame seeds. Great warm or at room temp — a lunchbox favorite the next day."},
        ],
    },
    {
        "id": "gen_soy_garlic_kfc",
        "title": "Soy-Garlic Korean Fried Chicken (Air-Fryer)",
        "source": "claude_chat",
        "source_url": "https://www.maangchi.com/recipe/easy-dakgangjeong",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 40,
        "prep_minutes": 15,
        "cook_minutes": 25,
        "cuisines": ["korean"],
        "diet_tags": [],
        "dish_types": ["main course"],
        "equipment": ["air_fryer"],
        "proteins": ["chicken"],
        "carbs": ["rice"],
        "ingredients": [
            {"name": "boneless skinless chicken thighs", "amount": 1.75, "unit": "lb", "aisle": "Meat",
             "group": "Chicken", "original_text": "1.75 lb chicken thighs, 1.5-inch pieces"},
            {"name": "cornstarch", "amount": 0.5, "unit": "cup", "aisle": "Baking",
             "group": "Chicken", "original_text": "1/2 cup cornstarch (the crispy coating)"},
            {"name": "garlic powder", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Chicken", "original_text": "1 tsp garlic powder"},
            {"name": "kosher salt", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Chicken", "original_text": "1 tsp kosher salt + black pepper"},
            {"name": "olive oil", "amount": 1, "unit": "tbsp", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "Chicken", "original_text": "1 tbsp oil (to spray/toss before air-frying)"},
            {"name": "low-sodium soy sauce", "amount": 3, "unit": "tbsp", "aisle": "Ethnic Foods",
             "group": "Soy-garlic glaze", "original_text": "3 tbsp low-sodium soy sauce"},
            {"name": "brown sugar", "amount": 3, "unit": "tbsp", "aisle": "Baking",
             "group": "Soy-garlic glaze", "original_text": "3 tbsp brown sugar"},
            {"name": "garlic", "amount": 6, "unit": "count", "aisle": "Produce",
             "group": "Soy-garlic glaze", "original_text": "6 garlic cloves, minced (yes, six — it's the name)"},
            {"name": "rice vinegar", "amount": 1, "unit": "tbsp", "aisle": "Ethnic Foods",
             "group": "Soy-garlic glaze", "original_text": "1 tbsp rice vinegar"},
            {"name": "honey", "amount": 1, "unit": "tbsp", "aisle": "Nut butters, Jams, and Honey",
             "group": "Soy-garlic glaze", "original_text": "1 tbsp honey"},
            {"name": "jasmine rice", "amount": 1.5, "unit": "cup", "aisle": "Pasta and Rice",
             "group": "For serving", "original_text": "1.5 cups rice (uncooked)"},
            {"name": "sesame seeds", "amount": 1, "unit": "tbsp", "aisle": "Spices and Seasonings",
             "group": "For serving", "original_text": "1 tbsp sesame seeds + sliced green onion"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Start the rice. Toss the chicken with 1 tsp garlic powder, 1 tsp salt, pepper, then dredge in the cornstarch until fully coated; shake off excess."},
            {"step_number": 2, "text": "Spray or toss the pieces with 1 tbsp oil. Air-fry at 400°F for 18-22 minutes, shaking twice, until deep golden and very crisp (165°F)."},
            {"step_number": 3, "text": "Meanwhile make the glaze: simmer 3 tbsp soy, 3 tbsp brown sugar, garlic, 1 tbsp vinegar, 1 tbsp honey in a large skillet 2-3 minutes until syrupy and thick enough to coat a spoon."},
            {"step_number": 4, "text": "Add the hot crispy chicken to the glaze; toss fast over low heat just until every piece is coated — do this right before serving so it stays crunchy."},
            {"step_number": 5, "text": "Tip onto a platter, scatter sesame seeds and green onion."},
            {"step_number": 6, "text": "Serve over rice. Soy-garlic = the non-spicy Korean fried chicken; sweet and sticky, no gochujang."},
        ],
    },
    # ---------------- THAI ----------------
    {
        "id": "gen_chicken_satay",
        "title": "Thai Chicken Satay with Peanut Sauce",
        "source": "claude_chat",
        "source_url": "https://www.recipetineats.com/thai-chicken-satay-peanut-sauce/",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 40,
        "prep_minutes": 25,
        "cook_minutes": 15,
        "cuisines": ["thai"],
        "diet_tags": ["gluten free"],
        "dish_types": ["main course"],
        "equipment": ["air_fryer", "grill"],
        "proteins": ["chicken"],
        "carbs": ["rice"],
        "ingredients": [
            {"name": "boneless skinless chicken thighs", "amount": 1.75, "unit": "lb", "aisle": "Meat",
             "group": "Satay", "original_text": "1.75 lb chicken thighs, cut into strips"},
            {"name": "coconut milk", "amount": 0.5, "unit": "cup", "aisle": "Ethnic Foods",
             "group": "Marinade", "original_text": "1/2 cup coconut milk"},
            {"name": "mild curry powder", "amount": 1, "unit": "tbsp", "aisle": "Spices and Seasonings",
             "group": "Marinade", "original_text": "1 tbsp mild curry powder"},
            {"name": "brown sugar", "amount": 1, "unit": "tbsp", "aisle": "Baking",
             "group": "Marinade", "original_text": "1 tbsp brown sugar"},
            {"name": "garlic", "amount": 3, "unit": "count", "aisle": "Produce",
             "group": "Marinade", "original_text": "3 garlic cloves, minced"},
            {"name": "kosher salt", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Marinade", "original_text": "1 tsp kosher salt"},
            {"name": "creamy peanut butter", "amount": 0.5, "unit": "cup", "aisle": "Nut butters, Jams, and Honey",
             "group": "Peanut sauce", "original_text": "1/2 cup creamy peanut butter"},
            {"name": "coconut milk", "amount": 0.75, "unit": "cup", "aisle": "Ethnic Foods",
             "group": "Peanut sauce", "original_text": "3/4 cup coconut milk (remaining from the can)"},
            {"name": "soy sauce", "amount": 1, "unit": "tbsp", "aisle": "Ethnic Foods",
             "group": "Peanut sauce", "original_text": "1 tbsp soy sauce"},
            {"name": "lime", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Peanut sauce", "original_text": "1 lime, juiced"},
            {"name": "jasmine rice", "amount": 1.5, "unit": "cup", "aisle": "Pasta and Rice",
             "group": "For serving", "original_text": "1.5 cups rice (uncooked)"},
            {"name": "cucumber", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "For serving", "original_text": "1 cucumber, sliced (quick cucumber salad)"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Marinate the chicken: 1/2 cup coconut milk, 1 tbsp curry powder, 1 tbsp brown sugar, garlic, 1 tsp salt. 20 minutes. Start the rice."},
            {"step_number": 2, "text": "Peanut sauce: whisk peanut butter, 3/4 cup coconut milk, 1 tbsp soy, lime juice, and 1 tsp curry powder in a small pot over low heat until smooth and pourable, 2-3 minutes. Thin with water as needed."},
            {"step_number": 3, "text": "Thread the chicken onto skewers, or leave as strips for the air fryer."},
            {"step_number": 4, "text": "Air-fry at 400°F for 12-14 minutes (or grill 4-5 min/side), turning once, until charred at the edges and 175°F."},
            {"step_number": 5, "text": "Quick cucumber salad: toss sliced cucumber with a splash of rice vinegar and a pinch of sugar."},
            {"step_number": 6, "text": "Serve the satay over rice with the peanut sauce for dunking and cucumber on the side. The kids will dip everything."},
        ],
    },
    {
        "id": "gen_pad_thai",
        "title": "Chicken Pad Thai",
        "source": "claude_chat",
        "source_url": "https://www.recipetineats.com/chicken-pad-thai/",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 30,
        "prep_minutes": 20,
        "cook_minutes": 10,
        "cuisines": ["thai"],
        "diet_tags": [],
        "dish_types": ["main course"],
        "equipment": ["wok", "skillet", "stovetop"],
        "proteins": ["chicken"],
        "carbs": ["pasta"],
        "ingredients": [
            {"name": "rice noodles", "amount": 8, "unit": "oz", "aisle": "Ethnic Foods",
             "group": "Noodles", "original_text": "8 oz flat rice noodles (pad thai width)"},
            {"name": "boneless skinless chicken thighs", "amount": 1, "unit": "lb", "aisle": "Meat",
             "group": "Stir-fry", "original_text": "1 lb chicken thighs, thin bite-size pieces"},
            {"name": "eggs", "amount": 2, "unit": "count", "aisle": "Eggs",
             "group": "Stir-fry", "original_text": "2 eggs"},
            {"name": "bean sprouts", "amount": 2, "unit": "cup", "aisle": "Produce",
             "group": "Stir-fry", "original_text": "2 cups bean sprouts"},
            {"name": "green onions", "amount": 4, "unit": "count", "aisle": "Produce",
             "group": "Stir-fry", "original_text": "4 green onions, cut into 1-inch lengths"},
            {"name": "garlic", "amount": 3, "unit": "count", "aisle": "Produce",
             "group": "Stir-fry", "original_text": "3 garlic cloves, minced"},
            {"name": "vegetable oil", "amount": 2, "unit": "tbsp", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "Stir-fry", "original_text": "2 tbsp vegetable oil"},
            {"name": "pad thai sauce", "amount": 0.5, "unit": "cup", "aisle": "Ethnic Foods",
             "group": "Sauce", "original_text": "1/2 cup store-bought pad thai sauce (house rule — bottled is excellent)"},
            {"name": "lime", "amount": 2, "unit": "count", "aisle": "Produce",
             "group": "For serving", "original_text": "2 limes, in wedges"},
            {"name": "roasted unsalted peanuts", "amount": 0.5, "unit": "cup", "aisle": "Nuts",
             "group": "For serving", "original_text": "1/2 cup roasted peanuts, crushed"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Soak the rice noodles in hot (not boiling) water 8-10 minutes until pliable but still firm; drain. They finish in the pan, so keep them underdone."},
            {"step_number": 2, "text": "Heat 1 tbsp oil in a wok over HIGH. Stir-fry the chicken 3-4 minutes until cooked through (165°F); push to one side."},
            {"step_number": 3, "text": "Add the last 1 tbsp oil and the garlic to the empty side, 15 seconds, then crack in the eggs and scramble 30 seconds."},
            {"step_number": 4, "text": "Add the drained noodles and 1/2 cup pad thai sauce. Toss constantly 2-3 minutes until the noodles soften and turn glossy — tongs work better than a spoon."},
            {"step_number": 5, "text": "Add the bean sprouts and green onions; toss 1 minute, keeping the sprouts crunchy."},
            {"step_number": 6, "text": "Pile onto plates; top with crushed peanuts and a lime wedge each. Squeeze the lime over — it makes the dish."},
        ],
    },
    {
        "id": "gen_thai_basil_chicken",
        "title": "Thai Basil Chicken (Mild Pad Krapow)",
        "source": "claude_chat",
        "source_url": "https://thewoksoflife.com/thai-basil-chicken-pad-krapow/",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 25,
        "prep_minutes": 15,
        "cook_minutes": 10,
        "cuisines": ["thai"],
        "diet_tags": [],
        "dish_types": ["main course"],
        "equipment": ["wok", "skillet", "stovetop"],
        "proteins": ["chicken"],
        "carbs": ["rice"],
        "ingredients": [
            {"name": "ground chicken", "amount": 1.5, "unit": "lb", "aisle": "Meat",
             "group": "Stir-fry", "original_text": "1.5 lb ground chicken (or finely chopped thighs)"},
            {"name": "thai basil", "amount": 2, "unit": "cup", "aisle": "Produce",
             "group": "Stir-fry", "original_text": "2 cups Thai basil leaves (regular basil works)"},
            {"name": "garlic", "amount": 5, "unit": "count", "aisle": "Produce",
             "group": "Stir-fry", "original_text": "5 garlic cloves, minced"},
            {"name": "red bell pepper", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Stir-fry", "original_text": "1 red bell pepper, thin strips"},
            {"name": "green beans", "amount": 0.5, "unit": "lb", "aisle": "Produce",
             "group": "Stir-fry", "original_text": "1/2 lb green beans, cut short"},
            {"name": "vegetable oil", "amount": 2, "unit": "tbsp", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "Stir-fry", "original_text": "2 tbsp vegetable oil"},
            {"name": "oyster sauce", "amount": 2, "unit": "tbsp", "aisle": "Ethnic Foods",
             "group": "Sauce", "original_text": "2 tbsp oyster sauce"},
            {"name": "soy sauce", "amount": 1.5, "unit": "tbsp", "aisle": "Ethnic Foods",
             "group": "Sauce", "original_text": "1.5 tbsp soy sauce"},
            {"name": "fish sauce", "amount": 1, "unit": "tbsp", "aisle": "Ethnic Foods",
             "group": "Sauce", "original_text": "1 tbsp fish sauce"},
            {"name": "sugar", "amount": 2, "unit": "tsp", "aisle": "Baking",
             "group": "Sauce", "original_text": "2 tsp sugar"},
            {"name": "jasmine rice", "amount": 1.5, "unit": "cup", "aisle": "Pasta and Rice",
             "group": "For serving", "original_text": "1.5 cups rice (uncooked)"},
            {"name": "eggs", "amount": 4, "unit": "count", "aisle": "Eggs",
             "group": "For serving", "original_text": "4 eggs, fried crispy (the traditional topping)"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Start the rice. Stir the sauce: 2 tbsp oyster sauce, 1.5 tbsp soy, 1 tbsp fish sauce, 2 tsp sugar. (Pad krapow is normally fiery — this version leaves the chilies out; sriracha at the table for adults.)"},
            {"step_number": 2, "text": "Heat 1 tbsp oil in a wok over HIGH. Stir-fry the green beans and bell pepper 2-3 minutes until crisp-tender; remove."},
            {"step_number": 3, "text": "Add the last 1 tbsp oil and the garlic, 15 seconds, then the ground chicken. Stir-fry 4-5 minutes, breaking it up, until cooked through and a little browned."},
            {"step_number": 4, "text": "Return the vegetables, pour in the sauce, and toss 1 minute until glossy."},
            {"step_number": 5, "text": "Kill the heat and fold in the basil just until wilted — 30 seconds, so it stays fragrant and green."},
            {"step_number": 6, "text": "Meanwhile fry the eggs crispy in a little hot oil. Serve the basil chicken over rice, each plate topped with a fried egg."},
        ],
    },
    {
        "id": "gen_thai_yellow_curry",
        "title": "Thai Yellow Chicken Curry with Potatoes",
        "source": "claude_chat",
        "source_url": "https://pinchofyum.com/thai-yellow-chicken-curry-with-potatoes",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 40,
        "prep_minutes": 15,
        "cook_minutes": 25,
        "cuisines": ["thai"],
        "diet_tags": ["gluten free"],
        "dish_types": ["main course"],
        "equipment": ["dutch_oven", "stovetop"],
        "proteins": ["chicken"],
        "carbs": ["potato"],
        "ingredients": [
            {"name": "boneless skinless chicken thighs", "amount": 1.5, "unit": "lb", "aisle": "Meat",
             "group": "Curry", "original_text": "1.5 lb chicken thighs, bite-size pieces"},
            {"name": "yellow curry paste", "amount": 4, "unit": "tbsp", "aisle": "Ethnic Foods",
             "group": "Curry", "original_text": "4 tbsp Thai yellow curry paste (mildest of the curry pastes)"},
            {"name": "coconut milk", "amount": 27, "unit": "oz", "aisle": "Ethnic Foods",
             "group": "Curry", "original_text": "2 cans (13.5 oz each) coconut milk"},
            {"name": "yukon gold potatoes", "amount": 1, "unit": "lb", "aisle": "Produce",
             "group": "Curry", "original_text": "1 lb Yukon Gold potatoes, 1-inch dice"},
            {"name": "carrots", "amount": 2, "unit": "count", "aisle": "Produce",
             "group": "Curry", "original_text": "2 carrots, thick coins"},
            {"name": "yellow onion", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Curry", "original_text": "1 onion, sliced"},
            {"name": "fish sauce", "amount": 1.5, "unit": "tbsp", "aisle": "Ethnic Foods",
             "group": "Curry", "original_text": "1.5 tbsp fish sauce"},
            {"name": "brown sugar", "amount": 1, "unit": "tbsp", "aisle": "Baking",
             "group": "Curry", "original_text": "1 tbsp brown sugar"},
            {"name": "vegetable oil", "amount": 1, "unit": "tbsp", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "Curry", "original_text": "1 tbsp vegetable oil"},
            {"name": "jasmine rice", "amount": 1.5, "unit": "cup", "aisle": "Pasta and Rice",
             "group": "For serving", "original_text": "1.5 cups rice (uncooked)"},
            {"name": "fresh cilantro", "amount": 0.25, "unit": "cup", "aisle": "Produce",
             "group": "For serving", "original_text": "1/4 cup cilantro + 1 lime in wedges"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Start the rice. Heat 1 tbsp oil in a dutch oven over medium; add 4 tbsp curry paste and fry 1-2 minutes until fragrant — blooming the paste in oil is the whole flavor base."},
            {"step_number": 2, "text": "Add the chicken and stir to coat in the paste; cook 3 minutes."},
            {"step_number": 3, "text": "Pour in both cans of coconut milk, then add the potatoes, carrots, and onion."},
            {"step_number": 4, "text": "Add 1.5 tbsp fish sauce and 1 tbsp brown sugar. Bring to a simmer."},
            {"step_number": 5, "text": "Simmer uncovered 20-25 minutes, stirring now and then, until the potatoes are fork-tender and the chicken reads 165°F and the sauce has thickened slightly."},
            {"step_number": 6, "text": "Taste — balance with a little more fish sauce (salt) or sugar. Serve over rice with cilantro and lime. Mild, creamy, kid-friendly."},
        ],
    },
]
