"""
wave2a_recipes.py — Wave 2 part A (12 of 23 gen_* concepts).

Rebuilt to the upgraded schema: serves 4, grouped ingredients (one unit
each), 6-8 substantive steps with quantities/temps/doneness, mild for kids,
store-bought sauces where sensible. source_url is set only when the real
source was verified; "" means adapted directly from the classic dish.

Apply with: python3 apply_wave.py wave2a_recipes.py [--apply]
"""

WAVE = [
    {
        "id": "gen_beef_kofta_rice",
        "title": "Beef Kofta with Cucumber Yogurt & Rice",
        "source": "claude_chat",
        "source_url": "https://www.recipetineats.com/lamb-koftas-yoghurt-dressing-2/",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 40,
        "prep_minutes": 20,
        "cook_minutes": 20,
        "cuisines": ["middle_eastern"],
        "diet_tags": [],
        "dish_types": ["main course"],
        "equipment": ["skillet", "stovetop"],
        "proteins": ["beef"],
        "carbs": ["rice"],
        "regen_pending": False,
        "ingredients": [
            {"name": "ground beef", "amount": 1.5, "unit": "lb", "aisle": "Meat",
             "group": "Koftas", "original_text": "1.5 lb ground beef (85/15)"},
            {"name": "yellow onion", "amount": 0.5, "unit": "count", "aisle": "Produce",
             "group": "Koftas", "original_text": "1/2 yellow onion, grated on a box grater"},
            {"name": "garlic", "amount": 3, "unit": "count", "aisle": "Produce",
             "group": "Koftas", "original_text": "3 garlic cloves, minced"},
            {"name": "ground cumin", "amount": 2, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Koftas", "original_text": "2 tsp ground cumin"},
            {"name": "ground coriander", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Koftas", "original_text": "1 tsp ground coriander"},
            {"name": "sweet paprika", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Koftas", "original_text": "1 tsp sweet paprika"},
            {"name": "fresh parsley", "amount": 0.25, "unit": "cup", "aisle": "Produce",
             "group": "Koftas", "original_text": "1/4 cup chopped parsley + more to serve"},
            {"name": "kosher salt", "amount": 1.25, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Koftas", "original_text": "1.25 tsp kosher salt + black pepper"},
            {"name": "plain greek yogurt", "amount": 1, "unit": "cup", "aisle": "Dairy",
             "group": "Cucumber yogurt", "original_text": "1 cup plain Greek yogurt"},
            {"name": "cucumber", "amount": 0.5, "unit": "count", "aisle": "Produce",
             "group": "Cucumber yogurt", "original_text": "1/2 cucumber, grated and squeezed dry"},
            {"name": "lemon", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Cucumber yogurt", "original_text": "1 lemon (half juiced into the yogurt, half in wedges)"},
            {"name": "basmati rice", "amount": 1.5, "unit": "cup", "aisle": "Pasta and Rice",
             "group": "For serving", "original_text": "1.5 cups basmati rice (uncooked)"},
            {"name": "cherry tomatoes", "amount": 1, "unit": "cup", "aisle": "Produce",
             "group": "For serving", "original_text": "1 cup cherry tomatoes, halved"},
            {"name": "olive oil", "amount": 1, "unit": "tbsp", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "For serving", "original_text": "1 tbsp olive oil (for the pan)"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Start the basmati rice (1.5 cups rice : 2.25 cups water, simmer covered 12 min, rest 10)."},
            {"step_number": 2, "text": "Mix the cucumber yogurt: 1 cup yogurt, the squeezed grated cucumber, juice of half the lemon, pinch of salt. Refrigerate."},
            {"step_number": 3, "text": "Mix koftas: beef, grated onion, garlic, 2 tsp cumin, 1 tsp coriander, 1 tsp paprika, 1/4 cup parsley, 1.25 tsp salt, pepper. Knead 1 minute until tacky — that keeps them together."},
            {"step_number": 4, "text": "Wet hands and shape into 12 small logs (about 3 inches each)."},
            {"step_number": 5, "text": "Heat 1 tbsp olive oil in a large skillet over medium-high. Cook koftas 8-10 minutes, turning every 2-3 minutes, until browned all over and cooked through (160°F, no pink in the center)."},
            {"step_number": 6, "text": "Fluff the rice and fold in the cherry tomatoes."},
            {"step_number": 7, "text": "Serve koftas over rice with a big spoonful of cucumber yogurt, lemon wedges, and extra parsley."},
        ],
    },
    {
        "id": "gen_black_bean_quesadillas",
        "title": "Black Bean & Sweet Potato Quesadillas",
        "source": "claude_chat",
        "source_url": "https://www.budgetbytes.com/hearty-black-bean-quesadillas/",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 35,
        "prep_minutes": 15,
        "cook_minutes": 20,
        "cuisines": ["mexican"],
        "diet_tags": ["vegetarian"],
        "dish_types": ["main course"],
        "equipment": ["skillet", "stovetop"],
        "proteins": ["plant"],
        "carbs": ["bread"],
        "regen_pending": False,
        "ingredients": [
            {"name": "sweet potato", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Filling", "original_text": "1 large sweet potato, peeled, 1/2-inch dice (about 2 cups)"},
            {"name": "black beans", "amount": 15, "unit": "oz", "aisle": "Canned and Jarred",
             "group": "Filling", "original_text": "1 can (15 oz) black beans, drained and rinsed"},
            {"name": "frozen corn", "amount": 1, "unit": "cup", "aisle": "Frozen",
             "group": "Filling", "original_text": "1 cup frozen corn"},
            {"name": "green onions", "amount": 3, "unit": "count", "aisle": "Produce",
             "group": "Filling", "original_text": "3 green onions, sliced"},
            {"name": "taco seasoning", "amount": 1.5, "unit": "tbsp", "aisle": "Spices and Seasonings",
             "group": "Filling", "original_text": "1.5 tbsp taco seasoning (mild)"},
            {"name": "shredded monterey jack", "amount": 2, "unit": "cup", "aisle": "Cheese",
             "group": "Filling", "original_text": "2 cups shredded Monterey Jack or Mexican blend"},
            {"name": "flour tortillas", "amount": 8, "unit": "count", "aisle": "Bakery",
             "group": "Assembly", "original_text": "8 medium (8-inch) flour tortillas"},
            {"name": "vegetable oil", "amount": 1, "unit": "tbsp", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "Assembly", "original_text": "1 tbsp vegetable oil (plus more for the pan)"},
            {"name": "salsa", "amount": 1, "unit": "cup", "aisle": "Canned and Jarred",
             "group": "For serving", "original_text": "store-bought salsa, for dipping"},
            {"name": "sour cream", "amount": 0.5, "unit": "cup", "aisle": "Dairy",
             "group": "For serving", "original_text": "1/2 cup sour cream"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Microwave the diced sweet potato with 2 tbsp water, covered, 4-5 minutes until fork-tender. Drain."},
            {"step_number": 2, "text": "Mash half the black beans in a bowl (helps the filling hold together), then stir in whole beans, sweet potato, corn, green onions, and 1.5 tbsp taco seasoning."},
            {"step_number": 3, "text": "Lay out 4 tortillas. Spread a quarter of the filling on each, top with 1/2 cup cheese, and press a second tortilla on top."},
            {"step_number": 4, "text": "Heat a dry large skillet over medium. Cook each quesadilla 2-3 minutes per side, pressing with a spatula, until deep golden and the cheese is fully melted. A teaspoon of oil in the pan makes them crispier."},
            {"step_number": 5, "text": "Rest 1 minute (the filling sets), then cut into wedges with a pizza cutter."},
            {"step_number": 6, "text": "Serve with salsa and sour cream. Leftover filling freezes well."},
        ],
    },
    {
        "id": "gen_coconut_chickpea_curry",
        "title": "Coconut Chickpea Curry",
        "source": "claude_chat",
        "source_url": "https://dishedbykate.com/coconut-chickpea-curry/",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 30,
        "prep_minutes": 10,
        "cook_minutes": 20,
        "cuisines": ["indian"],
        "diet_tags": ["vegetarian", "vegan", "gluten free"],
        "dish_types": ["main course"],
        "equipment": ["sauce_pan", "stovetop"],
        "proteins": ["plant"],
        "carbs": ["rice"],
        "regen_pending": False,
        "ingredients": [
            {"name": "chickpeas", "amount": 30, "unit": "oz", "aisle": "Canned and Jarred",
             "group": "Curry", "original_text": "2 cans (15 oz each) chickpeas, drained and rinsed"},
            {"name": "coconut milk", "amount": 13.5, "unit": "oz", "aisle": "Ethnic Foods",
             "group": "Curry", "original_text": "1 can (13.5 oz) full-fat coconut milk"},
            {"name": "diced tomatoes", "amount": 14.5, "unit": "oz", "aisle": "Canned and Jarred",
             "group": "Curry", "original_text": "1 can (14.5 oz) diced tomatoes"},
            {"name": "yellow onion", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Curry", "original_text": "1 yellow onion, finely chopped"},
            {"name": "garlic", "amount": 3, "unit": "count", "aisle": "Produce",
             "group": "Curry", "original_text": "3 garlic cloves, minced"},
            {"name": "fresh ginger", "amount": 1, "unit": "tbsp", "aisle": "Produce",
             "group": "Curry", "original_text": "1 tbsp fresh ginger, minced"},
            {"name": "mild curry powder", "amount": 2, "unit": "tbsp", "aisle": "Spices and Seasonings",
             "group": "Curry", "original_text": "2 tbsp mild curry powder"},
            {"name": "garam masala", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Curry", "original_text": "1 tsp garam masala"},
            {"name": "coconut oil", "amount": 1, "unit": "tbsp", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "Curry", "original_text": "1 tbsp coconut or vegetable oil"},
            {"name": "baby spinach", "amount": 3, "unit": "cup", "aisle": "Produce",
             "group": "Curry", "original_text": "3 cups baby spinach"},
            {"name": "kosher salt", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Curry", "original_text": "1 tsp kosher salt, plus to taste"},
            {"name": "basmati rice", "amount": 1.5, "unit": "cup", "aisle": "Pasta and Rice",
             "group": "For serving", "original_text": "1.5 cups basmati rice (uncooked)"},
            {"name": "fresh cilantro", "amount": 0.25, "unit": "cup", "aisle": "Produce",
             "group": "For serving", "original_text": "1/4 cup chopped cilantro"},
            {"name": "naan", "amount": 4, "unit": "count", "aisle": "Bakery",
             "group": "For serving", "original_text": "4 store-bought naan, warmed (optional)"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Start the rice (1.5 cups rice : 2.25 cups water, simmer covered 12 min, rest 10)."},
            {"step_number": 2, "text": "Heat 1 tbsp oil in a large saucepan over medium. Cook the onion 4-5 minutes until soft and translucent."},
            {"step_number": 3, "text": "Add garlic, ginger, 2 tbsp curry powder, and 1 tsp garam masala; stir 1 minute until fragrant — toasting the spices in the oil is where the flavor comes from."},
            {"step_number": 4, "text": "Add tomatoes, coconut milk, chickpeas, and 1 tsp salt. Simmer uncovered 12-15 minutes, stirring now and then, until slightly thickened and the chickpeas are creamy."},
            {"step_number": 5, "text": "Mash a few chickpeas against the side of the pot to thicken the sauce. Stir in the spinach until wilted, 1 minute."},
            {"step_number": 6, "text": "Taste — it should be rich and gently spiced; add salt or a squeeze of lemon if flat."},
            {"step_number": 7, "text": "Serve over rice with cilantro and warm naan."},
        ],
    },
    {
        "id": "gen_greek_shrimp_saganaki",
        "title": "Greek Shrimp Saganaki",
        "source": "claude_chat",
        "source_url": "https://www.themediterraneandish.com/greek-shrimp-recipe-with-tomato-and-feta/",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 30,
        "prep_minutes": 10,
        "cook_minutes": 20,
        "cuisines": ["greek"],
        "diet_tags": ["gluten free"],
        "dish_types": ["main course"],
        "equipment": ["skillet", "stovetop"],
        "proteins": ["shrimp"],
        "carbs": ["bread"],
        "regen_pending": False,
        "ingredients": [
            {"name": "large shrimp", "amount": 1.5, "unit": "lb", "aisle": "Seafood",
             "group": "Shrimp", "original_text": "1.5 lb large shrimp, peeled and deveined, tails off"},
            {"name": "olive oil", "amount": 3, "unit": "tbsp", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "Tomato sauce", "original_text": "3 tbsp olive oil"},
            {"name": "yellow onion", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Tomato sauce", "original_text": "1 yellow onion, finely chopped"},
            {"name": "garlic", "amount": 4, "unit": "count", "aisle": "Produce",
             "group": "Tomato sauce", "original_text": "4 garlic cloves, minced"},
            {"name": "crushed tomatoes", "amount": 28, "unit": "oz", "aisle": "Canned and Jarred",
             "group": "Tomato sauce", "original_text": "1 can (28 oz) crushed tomatoes"},
            {"name": "dried oregano", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Tomato sauce", "original_text": "1 tsp dried oregano"},
            {"name": "sugar", "amount": 0.5, "unit": "tsp", "aisle": "Baking",
             "group": "Tomato sauce", "original_text": "1/2 tsp sugar (balances the tomatoes)"},
            {"name": "kosher salt", "amount": 0.75, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Tomato sauce", "original_text": "3/4 tsp kosher salt + black pepper"},
            {"name": "feta cheese", "amount": 6, "unit": "oz", "aisle": "Cheese",
             "group": "To finish", "original_text": "6 oz feta, crumbled in big chunks"},
            {"name": "fresh parsley", "amount": 0.25, "unit": "cup", "aisle": "Produce",
             "group": "To finish", "original_text": "1/4 cup chopped parsley (or dill)"},
            {"name": "lemon", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "To finish", "original_text": "1 lemon, in wedges"},
            {"name": "crusty bread", "amount": 1, "unit": "count", "aisle": "Bakery",
             "group": "For serving", "original_text": "1 crusty baguette or loaf, for scooping (or cooked orzo)"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Pat the shrimp very dry and season lightly with salt. Heat the oven broiler if your skillet is oven-safe (optional finish)."},
            {"step_number": 2, "text": "Heat 3 tbsp olive oil in a large skillet over medium. Cook the onion 4-5 minutes until soft; add garlic and 1 tsp oregano, stir 1 minute."},
            {"step_number": 3, "text": "Pour in the crushed tomatoes with 1/2 tsp sugar, 3/4 tsp salt, and pepper. Simmer 10 minutes until thickened enough that a spoon leaves a trail."},
            {"step_number": 4, "text": "Nestle the shrimp into the sauce in one layer. Cook 2-3 minutes per side, just until pink and curled into loose C-shapes — tight O-shapes mean overcooked."},
            {"step_number": 5, "text": "Scatter the feta chunks over the top. Cover 1 minute (or broil 2 minutes) until the feta is soft and creamy."},
            {"step_number": 6, "text": "Finish with parsley and a squeeze of lemon. Bring the skillet to the table with bread for scooping."},
        ],
    },
    {
        "id": "gen_harissa_chicken_chickpeas",
        "title": "Sheet-Pan Harissa Chicken & Chickpeas",
        "source": "claude_chat",
        "source_url": "https://www.food.com/recipe/pan-roasted-chicken-with-harissa-chickpeas-512488",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 50,
        "prep_minutes": 15,
        "cook_minutes": 35,
        "cuisines": ["middle_eastern"],
        "diet_tags": ["gluten free"],
        "dish_types": ["main course"],
        "equipment": ["oven", "sheet_pan"],
        "proteins": ["chicken"],
        "carbs": ["grain"],
        "regen_pending": False,
        "ingredients": [
            {"name": "boneless skinless chicken thighs", "amount": 2, "unit": "lb", "aisle": "Meat",
             "group": "Chicken", "original_text": "2 lb boneless skinless chicken thighs"},
            {"name": "mild harissa paste", "amount": 2, "unit": "tbsp", "aisle": "Ethnic Foods",
             "group": "Chicken", "original_text": "2 tbsp mild harissa paste (jarred — brands vary in heat, taste first)"},
            {"name": "olive oil", "amount": 3, "unit": "tbsp", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "Chicken", "original_text": "3 tbsp olive oil, divided"},
            {"name": "honey", "amount": 1, "unit": "tsp", "aisle": "Nut butters, Jams, and Honey",
             "group": "Chicken", "original_text": "1 tsp honey (rounds out the harissa)"},
            {"name": "kosher salt", "amount": 1.25, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Chicken", "original_text": "1.25 tsp kosher salt"},
            {"name": "chickpeas", "amount": 30, "unit": "oz", "aisle": "Canned and Jarred",
             "group": "Vegetables", "original_text": "2 cans (15 oz each) chickpeas, drained and patted dry"},
            {"name": "red onion", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Vegetables", "original_text": "1 red onion, cut into wedges"},
            {"name": "zucchini", "amount": 2, "unit": "count", "aisle": "Produce",
             "group": "Vegetables", "original_text": "2 zucchini, thick half-moons"},
            {"name": "ground cumin", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Vegetables", "original_text": "1 tsp ground cumin"},
            {"name": "plain greek yogurt", "amount": 0.75, "unit": "cup", "aisle": "Dairy",
             "group": "For serving", "original_text": "3/4 cup plain Greek yogurt (cooling, for the kids especially)"},
            {"name": "couscous", "amount": 1.5, "unit": "cup", "aisle": "Pasta and Rice",
             "group": "For serving", "original_text": "1.5 cups couscous"},
            {"name": "fresh mint", "amount": 0.25, "unit": "cup", "aisle": "Produce",
             "group": "For serving", "original_text": "1/4 cup mint or parsley leaves"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Heat the oven to 425°F. Whisk 2 tbsp harissa, 2 tbsp olive oil, 1 tsp honey, and 1.25 tsp salt; toss with the chicken thighs."},
            {"step_number": 2, "text": "Toss the dried chickpeas, red onion, and zucchini on a large sheet pan with the remaining 1 tbsp oil, 1 tsp cumin, and a pinch of salt. Dry chickpeas = crispy chickpeas."},
            {"step_number": 3, "text": "Make room and lay the chicken thighs flat among the vegetables, smooth side up."},
            {"step_number": 4, "text": "Roast 30-35 minutes until the chicken reads 175°F and the chickpeas are browned and starting to crisp. Stir the vegetables once halfway."},
            {"step_number": 5, "text": "Meanwhile make the couscous: 1.5 cups couscous + 1.75 cups boiling water, cover 5 minutes, fluff."},
            {"step_number": 6, "text": "Serve over couscous with a spoonful of yogurt on each plate and mint scattered over. Kids' plates: extra yogurt, chicken from the milder middle of the pan."},
        ],
    },
    {
        "id": "gen_indian_chicken_korma",
        "title": "Mild Chicken Korma",
        "source": "claude_chat",
        "source_url": "https://www.indianhealthyrecipes.com/chicken-korma-recipe/",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 45,
        "prep_minutes": 20,
        "cook_minutes": 25,
        "cuisines": ["indian"],
        "diet_tags": ["gluten free"],
        "dish_types": ["main course"],
        "equipment": ["skillet", "stovetop"],
        "proteins": ["chicken"],
        "carbs": ["rice"],
        "regen_pending": False,
        "ingredients": [
            {"name": "boneless skinless chicken thighs", "amount": 1.75, "unit": "lb", "aisle": "Meat",
             "group": "Chicken", "original_text": "1.75 lb boneless skinless chicken thighs, bite-size pieces"},
            {"name": "plain greek yogurt", "amount": 0.5, "unit": "cup", "aisle": "Dairy",
             "group": "Chicken", "original_text": "1/2 cup plain yogurt (marinade)"},
            {"name": "garam masala", "amount": 2, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Chicken", "original_text": "2 tsp garam masala (marinade)"},
            {"name": "yellow onion", "amount": 2, "unit": "count", "aisle": "Produce",
             "group": "Korma sauce", "original_text": "2 yellow onions, sliced"},
            {"name": "garlic", "amount": 4, "unit": "count", "aisle": "Produce",
             "group": "Korma sauce", "original_text": "4 garlic cloves"},
            {"name": "fresh ginger", "amount": 1, "unit": "tbsp", "aisle": "Produce",
             "group": "Korma sauce", "original_text": "1 tbsp fresh ginger, chopped"},
            {"name": "cashews", "amount": 0.5, "unit": "cup", "aisle": "Nuts",
             "group": "Korma sauce", "original_text": "1/2 cup raw cashews (the body of the sauce)"},
            {"name": "ground coriander", "amount": 2, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Korma sauce", "original_text": "2 tsp ground coriander"},
            {"name": "ground turmeric", "amount": 0.5, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Korma sauce", "original_text": "1/2 tsp turmeric"},
            {"name": "ground cardamom", "amount": 0.25, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Korma sauce", "original_text": "1/4 tsp ground cardamom"},
            {"name": "heavy cream", "amount": 0.5, "unit": "cup", "aisle": "Dairy",
             "group": "Korma sauce", "original_text": "1/2 cup heavy cream"},
            {"name": "ghee", "amount": 2, "unit": "tbsp", "aisle": "Ethnic Foods",
             "group": "Korma sauce", "original_text": "2 tbsp ghee or butter"},
            {"name": "kosher salt", "amount": 1.25, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Korma sauce", "original_text": "1.25 tsp kosher salt"},
            {"name": "basmati rice", "amount": 1.5, "unit": "cup", "aisle": "Pasta and Rice",
             "group": "For serving", "original_text": "1.5 cups basmati rice (uncooked)"},
            {"name": "fresh cilantro", "amount": 0.25, "unit": "cup", "aisle": "Produce",
             "group": "For serving", "original_text": "1/4 cup cilantro leaves"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Toss the chicken with 1/2 cup yogurt and 2 tsp garam masala; marinate while you make the sauce base (20+ minutes)."},
            {"step_number": 2, "text": "Simmer the cashews in 1 cup hot water 15 minutes to soften. Start the rice."},
            {"step_number": 3, "text": "Melt 1 tbsp ghee in a large skillet over medium-high; cook the sliced onions 8-10 minutes until deeply golden (not just soft — the color is the flavor)."},
            {"step_number": 4, "text": "Blend the onions, drained cashews, garlic, and ginger with 3/4 cup water until completely smooth."},
            {"step_number": 5, "text": "Melt the remaining 1 tbsp ghee in the same skillet over medium-high. Add the chicken with its marinade; cook 5-6 minutes, stirring, until the yogurt coating no longer looks raw."},
            {"step_number": 6, "text": "Add the cashew-onion paste, 2 tsp coriander, 1/2 tsp turmeric, 1/4 tsp cardamom, and 1.25 tsp salt. Simmer gently 10 minutes, splashing in water if it gets thicker than gravy."},
            {"step_number": 7, "text": "Stir in 1/2 cup cream; warm through without boiling. The chicken should read 165°F."},
            {"step_number": 8, "text": "Serve over basmati rice with cilantro. Mild, creamy, and kid-safe by design."},
        ],
    },
    {
        "id": "gen_indian_paneer_tikka",
        "title": "Paneer Tikka Masala",
        "source": "claude_chat",
        "source_url": "https://www.indianhealthyrecipes.com/paneer-tikka-masala-recipe-sanjeev-kapoor/",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 40,
        "prep_minutes": 15,
        "cook_minutes": 25,
        "cuisines": ["indian"],
        "diet_tags": ["vegetarian", "gluten free"],
        "dish_types": ["main course"],
        "equipment": ["skillet", "stovetop"],
        "proteins": ["plant"],
        "carbs": ["rice"],
        "regen_pending": False,
        "ingredients": [
            {"name": "paneer", "amount": 14, "unit": "oz", "aisle": "Cheese",
             "group": "Paneer", "original_text": "14 oz paneer, 1-inch cubes"},
            {"name": "plain greek yogurt", "amount": 0.33, "unit": "cup", "aisle": "Dairy",
             "group": "Paneer", "original_text": "1/3 cup plain yogurt (paneer marinade)"},
            {"name": "garam masala", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Paneer", "original_text": "1 tsp garam masala (marinade)"},
            {"name": "yellow onion", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Masala sauce", "original_text": "1 yellow onion, finely chopped"},
            {"name": "garlic", "amount": 4, "unit": "count", "aisle": "Produce",
             "group": "Masala sauce", "original_text": "4 garlic cloves, minced"},
            {"name": "fresh ginger", "amount": 1, "unit": "tbsp", "aisle": "Produce",
             "group": "Masala sauce", "original_text": "1 tbsp fresh ginger, minced"},
            {"name": "tomato passata", "amount": 1.5, "unit": "cup", "aisle": "Canned and Jarred",
             "group": "Masala sauce", "original_text": "1.5 cups tomato passata (tomato puree)"},
            {"name": "ground coriander", "amount": 2, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Masala sauce", "original_text": "2 tsp ground coriander"},
            {"name": "ground cumin", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Masala sauce", "original_text": "1 tsp ground cumin"},
            {"name": "sweet paprika", "amount": 2, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Masala sauce", "original_text": "2 tsp sweet paprika (color without heat)"},
            {"name": "heavy cream", "amount": 0.5, "unit": "cup", "aisle": "Dairy",
             "group": "Masala sauce", "original_text": "1/2 cup heavy cream"},
            {"name": "butter", "amount": 2, "unit": "tbsp", "aisle": "Dairy",
             "group": "Masala sauce", "original_text": "2 tbsp butter"},
            {"name": "sugar", "amount": 1, "unit": "tsp", "aisle": "Baking",
             "group": "Masala sauce", "original_text": "1 tsp sugar"},
            {"name": "kosher salt", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Masala sauce", "original_text": "1 tsp kosher salt"},
            {"name": "frozen peas", "amount": 1, "unit": "cup", "aisle": "Frozen",
             "group": "Masala sauce", "original_text": "1 cup frozen peas"},
            {"name": "basmati rice", "amount": 1.5, "unit": "cup", "aisle": "Pasta and Rice",
             "group": "For serving", "original_text": "1.5 cups basmati rice (uncooked)"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Start the rice. Toss the paneer cubes with 1/3 cup yogurt and 1 tsp garam masala."},
            {"step_number": 2, "text": "Melt 1 tbsp butter in a large nonstick skillet over medium-high. Brown the paneer 1-2 minutes per side until golden at the edges; remove. Don't crowd — it steams instead of browning."},
            {"step_number": 3, "text": "Melt the remaining 1 tbsp butter; cook the onion 4-5 minutes until soft. Add garlic and ginger, stir 1 minute."},
            {"step_number": 4, "text": "Add 2 tsp coriander, 1 tsp cumin, and 2 tsp paprika; toast 30 seconds. Pour in the passata with 1/2 cup water, 1 tsp sugar, and 1 tsp salt."},
            {"step_number": 5, "text": "Simmer 8-10 minutes until the sauce darkens and thickens to coat a spoon."},
            {"step_number": 6, "text": "Stir in the cream and peas; simmer 2 minutes. Return the paneer and warm through 2 minutes more."},
            {"step_number": 7, "text": "Serve over basmati rice. (Adults: chili crisp at the table if you want heat.)"},
        ],
    },
    {
        "id": "gen_me_beef_arayes",
        "title": "Spiced Beef Arayes (Stuffed Pita)",
        "source": "claude_chat",
        "source_url": "",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 35,
        "prep_minutes": 15,
        "cook_minutes": 20,
        "cuisines": ["middle_eastern"],
        "diet_tags": [],
        "dish_types": ["main course"],
        "equipment": ["air_fryer", "skillet"],
        "proteins": ["beef"],
        "carbs": ["bread"],
        "regen_pending": False,
        "ingredients": [
            {"name": "ground beef", "amount": 1.25, "unit": "lb", "aisle": "Meat",
             "group": "Filling", "original_text": "1.25 lb ground beef (85/15)"},
            {"name": "yellow onion", "amount": 0.5, "unit": "count", "aisle": "Produce",
             "group": "Filling", "original_text": "1/2 yellow onion, grated"},
            {"name": "fresh parsley", "amount": 0.5, "unit": "cup", "aisle": "Produce",
             "group": "Filling", "original_text": "1/2 cup parsley, finely chopped"},
            {"name": "garlic", "amount": 3, "unit": "count", "aisle": "Produce",
             "group": "Filling", "original_text": "3 garlic cloves, minced"},
            {"name": "ground cumin", "amount": 1.5, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Filling", "original_text": "1.5 tsp ground cumin"},
            {"name": "ground allspice", "amount": 0.5, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Filling", "original_text": "1/2 tsp ground allspice"},
            {"name": "sweet paprika", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Filling", "original_text": "1 tsp sweet paprika"},
            {"name": "kosher salt", "amount": 1.25, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Filling", "original_text": "1.25 tsp kosher salt + black pepper"},
            {"name": "pita bread", "amount": 4, "unit": "count", "aisle": "Bakery",
             "group": "Assembly", "original_text": "4 pita breads, halved into pockets"},
            {"name": "olive oil", "amount": 2, "unit": "tbsp", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "Assembly", "original_text": "2 tbsp olive oil, for brushing"},
            {"name": "tzatziki", "amount": 8, "unit": "oz", "aisle": "Refrigerated",
             "group": "For serving", "original_text": "store-bought tzatziki or hummus"},
            {"name": "cucumber", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "For serving", "original_text": "1 cucumber, sliced, + cherry tomatoes for a quick side salad"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Mix the filling: beef, grated onion, parsley, garlic, 1.5 tsp cumin, 1/2 tsp allspice, 1 tsp paprika, 1.25 tsp salt, pepper. Mix just until combined."},
            {"step_number": 2, "text": "Open each pita half and spread about 1/3 cup filling inside in a thin, even layer pressed to the edges — thin layers cook through; thick lumps don't."},
            {"step_number": 3, "text": "Brush both sides of each stuffed pita with olive oil."},
            {"step_number": 4, "text": "Air-fry at 380°F for 10-12 minutes, flipping halfway, until the bread is deep golden and crisp and the meat reads 160°F. (Skillet: medium heat, 4-5 minutes per side, pressing gently.)"},
            {"step_number": 5, "text": "Rest 2 minutes, cut each half into wedges."},
            {"step_number": 6, "text": "Serve with tzatziki for dipping and the cucumber-tomato salad alongside."},
        ],
    },
    {
        "id": "gen_me_chicken_shawarma_bowls",
        "title": "Air-Fryer Chicken Shawarma Bowls",
        "source": "claude_chat",
        "source_url": "https://www.recipetineats.com/chicken-sharwama-middle-eastern/",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 45,
        "prep_minutes": 20,
        "cook_minutes": 25,
        "cuisines": ["middle_eastern"],
        "diet_tags": ["gluten free"],
        "dish_types": ["main course"],
        "equipment": ["air_fryer"],
        "proteins": ["chicken"],
        "carbs": ["rice"],
        "regen_pending": False,
        "ingredients": [
            {"name": "boneless skinless chicken thighs", "amount": 2, "unit": "lb", "aisle": "Meat",
             "group": "Shawarma chicken", "original_text": "2 lb boneless skinless chicken thighs"},
            {"name": "olive oil", "amount": 3, "unit": "tbsp", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "Shawarma chicken", "original_text": "3 tbsp olive oil"},
            {"name": "lemon", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Shawarma chicken", "original_text": "1 lemon, juiced (about 3 tbsp)"},
            {"name": "ground cumin", "amount": 2, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Shawarma chicken", "original_text": "2 tsp ground cumin"},
            {"name": "ground coriander", "amount": 2, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Shawarma chicken", "original_text": "2 tsp ground coriander"},
            {"name": "sweet paprika", "amount": 2, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Shawarma chicken", "original_text": "2 tsp sweet paprika"},
            {"name": "ground turmeric", "amount": 0.5, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Shawarma chicken", "original_text": "1/2 tsp turmeric"},
            {"name": "ground cinnamon", "amount": 0.25, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Shawarma chicken", "original_text": "1/4 tsp cinnamon"},
            {"name": "garlic", "amount": 4, "unit": "count", "aisle": "Produce",
             "group": "Shawarma chicken", "original_text": "4 garlic cloves, minced"},
            {"name": "kosher salt", "amount": 1.5, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Shawarma chicken", "original_text": "1.5 tsp kosher salt"},
            {"name": "basmati rice", "amount": 1.5, "unit": "cup", "aisle": "Pasta and Rice",
             "group": "Bowls", "original_text": "1.5 cups basmati rice (uncooked)"},
            {"name": "cucumber", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Bowls", "original_text": "1 cucumber, diced"},
            {"name": "cherry tomatoes", "amount": 2, "unit": "cup", "aisle": "Produce",
             "group": "Bowls", "original_text": "2 cups cherry tomatoes, halved"},
            {"name": "red onion", "amount": 0.5, "unit": "count", "aisle": "Produce",
             "group": "Bowls", "original_text": "1/2 red onion, thinly sliced"},
            {"name": "tzatziki", "amount": 8, "unit": "oz", "aisle": "Refrigerated",
             "group": "Bowls", "original_text": "store-bought tzatziki (or hummus)"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Marinate the chicken: olive oil, lemon juice, garlic, 2 tsp cumin, 2 tsp coriander, 2 tsp paprika, 1/2 tsp turmeric, 1/4 tsp cinnamon, 1.5 tsp salt. 20 minutes on the counter or up to overnight in the fridge."},
            {"step_number": 2, "text": "Start the rice (1.5 cups rice : 2.25 cups water, simmer covered 12 min, rest 10)."},
            {"step_number": 3, "text": "Air-fry the thighs at 380°F for 16-18 minutes, flipping once, until charred at the edges and 175°F at the thickest part. Work in two batches if needed — overlapping thighs steam."},
            {"step_number": 4, "text": "While the chicken cooks, dice the cucumber, halve the tomatoes, slice the onion."},
            {"step_number": 5, "text": "Rest the chicken 5 minutes, then slice into strips."},
            {"step_number": 6, "text": "Build bowls: rice, chicken, vegetables, big spoonful of tzatziki. The spice blend is warm, not hot — kid-safe as is."},
        ],
    },
    {
        "id": "gen_me_chickpea_shakshuka",
        "title": "Chickpea Shakshuka with Feta",
        "source": "claude_chat",
        "source_url": "https://downshiftology.com/recipes/shakshuka/",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 35,
        "prep_minutes": 10,
        "cook_minutes": 25,
        "cuisines": ["middle_eastern"],
        "diet_tags": ["vegetarian", "gluten free"],
        "dish_types": ["main course", "breakfast"],
        "equipment": ["skillet", "stovetop"],
        "proteins": ["plant"],
        "carbs": ["bread"],
        "regen_pending": False,
        "ingredients": [
            {"name": "olive oil", "amount": 2, "unit": "tbsp", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "Tomato base", "original_text": "2 tbsp olive oil"},
            {"name": "yellow onion", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Tomato base", "original_text": "1 yellow onion, chopped"},
            {"name": "red bell pepper", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Tomato base", "original_text": "1 red bell pepper, chopped"},
            {"name": "garlic", "amount": 3, "unit": "count", "aisle": "Produce",
             "group": "Tomato base", "original_text": "3 garlic cloves, minced"},
            {"name": "sweet paprika", "amount": 2, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Tomato base", "original_text": "2 tsp sweet paprika"},
            {"name": "ground cumin", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Tomato base", "original_text": "1 tsp ground cumin"},
            {"name": "crushed tomatoes", "amount": 28, "unit": "oz", "aisle": "Canned and Jarred",
             "group": "Tomato base", "original_text": "1 can (28 oz) crushed tomatoes"},
            {"name": "chickpeas", "amount": 15, "unit": "oz", "aisle": "Canned and Jarred",
             "group": "Tomato base", "original_text": "1 can (15 oz) chickpeas, drained (makes it dinner, not just brunch)"},
            {"name": "kosher salt", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Tomato base", "original_text": "1 tsp kosher salt + black pepper"},
            {"name": "eggs", "amount": 6, "unit": "count", "aisle": "Eggs",
             "group": "To finish", "original_text": "6 eggs"},
            {"name": "feta cheese", "amount": 4, "unit": "oz", "aisle": "Cheese",
             "group": "To finish", "original_text": "4 oz feta, crumbled"},
            {"name": "fresh parsley", "amount": 0.25, "unit": "cup", "aisle": "Produce",
             "group": "To finish", "original_text": "1/4 cup chopped parsley or cilantro"},
            {"name": "crusty bread", "amount": 1, "unit": "count", "aisle": "Bakery",
             "group": "For serving", "original_text": "1 loaf crusty bread or warm pita"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Heat 2 tbsp olive oil in a large deep skillet (with a lid) over medium. Cook the onion and bell pepper 6-7 minutes until soft."},
            {"step_number": 2, "text": "Add garlic, 2 tsp paprika, and 1 tsp cumin; stir 1 minute until fragrant."},
            {"step_number": 3, "text": "Pour in the crushed tomatoes and chickpeas with 1 tsp salt and pepper. Simmer 10 minutes until slightly thickened — it should mound on a spoon, not run."},
            {"step_number": 4, "text": "With a spoon, make 6 wells in the sauce. Crack an egg into each."},
            {"step_number": 5, "text": "Cover and cook 6-8 minutes: whites set, yolks still soft. Check at 6 — they go from jammy to hard fast."},
            {"step_number": 6, "text": "Scatter feta and parsley over the top."},
            {"step_number": 7, "text": "Bring the skillet to the table with bread for scooping. (Breakfast-for-dinner night, zero apologies.)"},
        ],
    },
    {
        "id": "gen_me_tahini_salmon",
        "title": "Tahini-Roasted Salmon with Couscous",
        "source": "claude_chat",
        "source_url": "",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 30,
        "prep_minutes": 10,
        "cook_minutes": 20,
        "cuisines": ["middle_eastern"],
        "diet_tags": [],
        "dish_types": ["main course"],
        "equipment": ["oven", "sheet_pan"],
        "proteins": ["fish"],
        "carbs": ["grain"],
        "regen_pending": False,
        "ingredients": [
            {"name": "salmon fillets", "amount": 4, "unit": "count", "aisle": "Seafood",
             "group": "Salmon", "original_text": "4 salmon fillets (about 6 oz each), skin on"},
            {"name": "tahini", "amount": 0.33, "unit": "cup", "aisle": "Ethnic Foods",
             "group": "Tahini sauce", "original_text": "1/3 cup tahini, well stirred"},
            {"name": "lemon", "amount": 2, "unit": "count", "aisle": "Produce",
             "group": "Tahini sauce", "original_text": "2 lemons (1 juiced into the sauce, 1 in wedges)"},
            {"name": "garlic", "amount": 2, "unit": "count", "aisle": "Produce",
             "group": "Tahini sauce", "original_text": "2 garlic cloves, grated"},
            {"name": "ground cumin", "amount": 0.5, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Tahini sauce", "original_text": "1/2 tsp ground cumin"},
            {"name": "kosher salt", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Tahini sauce", "original_text": "1 tsp kosher salt, divided"},
            {"name": "broccolini", "amount": 1, "unit": "lb", "aisle": "Produce",
             "group": "Vegetables", "original_text": "1 lb broccolini or green beans, trimmed"},
            {"name": "olive oil", "amount": 2, "unit": "tbsp", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "Vegetables", "original_text": "2 tbsp olive oil"},
            {"name": "couscous", "amount": 1.5, "unit": "cup", "aisle": "Pasta and Rice",
             "group": "For serving", "original_text": "1.5 cups couscous"},
            {"name": "fresh parsley", "amount": 0.25, "unit": "cup", "aisle": "Produce",
             "group": "For serving", "original_text": "1/4 cup chopped parsley"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Heat the oven to 425°F. Whisk the tahini sauce: 1/3 cup tahini, juice of 1 lemon, grated garlic, 1/2 tsp cumin, 1/2 tsp salt, and 4-6 tbsp warm water until pourable like heavy cream (it seizes, then smooths — keep whisking)."},
            {"step_number": 2, "text": "Toss the broccolini with 2 tbsp olive oil and a pinch of salt on a sheet pan; push to the sides."},
            {"step_number": 3, "text": "Pat the salmon dry, season with the remaining 1/2 tsp salt, and place skin-down in the center. Spoon a third of the tahini sauce over the fillets."},
            {"step_number": 4, "text": "Roast 12-14 minutes until the salmon flakes at the thickest part (125°F for medium) and the broccolini is charred at the tips."},
            {"step_number": 5, "text": "Meanwhile make the couscous: 1.5 cups couscous + 1.75 cups boiling water, cover 5 minutes, fluff."},
            {"step_number": 6, "text": "Plate salmon and vegetables over couscous; drizzle with the remaining tahini sauce, scatter parsley, serve with lemon wedges."},
        ],
    },
    {
        "id": "gen_moroccan_beef_lentil_soup",
        "title": "Moroccan Beef & Red Lentil Soup",
        "source": "claude_chat",
        "source_url": "https://www.themediterraneandish.com/harira-recipe/",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 50,
        "prep_minutes": 15,
        "cook_minutes": 35,
        "cuisines": ["moroccan"],
        "diet_tags": ["gluten free"],
        "dish_types": ["main course", "soup"],
        "equipment": ["dutch_oven", "stovetop"],
        "proteins": ["beef"],
        "carbs": ["grain"],
        "regen_pending": False,
        "ingredients": [
            {"name": "ground beef", "amount": 1, "unit": "lb", "aisle": "Meat",
             "group": "Soup", "original_text": "1 lb ground beef"},
            {"name": "yellow onion", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Soup", "original_text": "1 yellow onion, chopped"},
            {"name": "carrots", "amount": 2, "unit": "count", "aisle": "Produce",
             "group": "Soup", "original_text": "2 carrots, diced"},
            {"name": "celery", "amount": 2, "unit": "count", "aisle": "Produce",
             "group": "Soup", "original_text": "2 celery stalks, diced"},
            {"name": "garlic", "amount": 3, "unit": "count", "aisle": "Produce",
             "group": "Soup", "original_text": "3 garlic cloves, minced"},
            {"name": "red lentils", "amount": 1, "unit": "cup", "aisle": "Pasta and Rice",
             "group": "Soup", "original_text": "1 cup red lentils, rinsed"},
            {"name": "diced tomatoes", "amount": 14.5, "unit": "oz", "aisle": "Canned and Jarred",
             "group": "Soup", "original_text": "1 can (14.5 oz) diced tomatoes"},
            {"name": "beef broth", "amount": 6, "unit": "cup", "aisle": "Canned and Jarred",
             "group": "Soup", "original_text": "6 cups beef broth"},
            {"name": "ground cumin", "amount": 2, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Spices (harira-style)", "original_text": "2 tsp ground cumin"},
            {"name": "ground turmeric", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Spices (harira-style)", "original_text": "1 tsp turmeric"},
            {"name": "ground cinnamon", "amount": 0.5, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Spices (harira-style)", "original_text": "1/2 tsp cinnamon"},
            {"name": "ground ginger", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Spices (harira-style)", "original_text": "1 tsp ground ginger"},
            {"name": "kosher salt", "amount": 1.5, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Spices (harira-style)", "original_text": "1.5 tsp kosher salt + black pepper"},
            {"name": "fresh cilantro", "amount": 0.5, "unit": "cup", "aisle": "Produce",
             "group": "To finish", "original_text": "1/2 cup chopped cilantro + parsley"},
            {"name": "lemon", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "To finish", "original_text": "1 lemon, in wedges (a squeeze wakes the whole bowl up)"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Brown the ground beef in a dutch oven over medium-high, breaking it up, 5-6 minutes until no longer pink. Spoon off excess fat, leaving about 1 tbsp."},
            {"step_number": 2, "text": "Add onion, carrots, and celery; cook 5 minutes until softening. Add garlic, stir 1 minute."},
            {"step_number": 3, "text": "Add the spices — 2 tsp cumin, 1 tsp turmeric, 1/2 tsp cinnamon, 1 tsp ginger, 1.5 tsp salt — and stir 30 seconds to bloom in the fat."},
            {"step_number": 4, "text": "Add lentils, tomatoes, and 6 cups broth. Bring to a boil, then simmer uncovered 25 minutes, stirring occasionally, until the lentils have broken down and thickened the soup."},
            {"step_number": 5, "text": "The texture should be hearty, almost stew-like; splash in water if it's too thick. Taste for salt."},
            {"step_number": 6, "text": "Stir in the herbs off the heat. Serve with lemon wedges — don't skip the squeeze."},
        ],
    },
]
