"""
wave4a_recipes.py — Wave 4 part A: new user-selected recipes (American 4,
Italian 4, Fish 3 = 11). All NEW ids, enter unproven (times_cooked 0 → no
made_it scoring bonus until first cook). Same schema/quality bar as prior
waves: serves 4, grouped ingredients, one unit each, mild, store-bought
sauces where one exists. source_url set only where a real source was found.

Apply: python3 apply_wave.py wave4a_recipes.py [--apply]
"""

WAVE = [
    # ---------------- AMERICAN ----------------
    {
        "id": "gen_bbq_pulled_chicken",
        "title": "Slow-Cooker BBQ Pulled Chicken Sandwiches",
        "source": "claude_chat",
        "source_url": "https://therealfooddietitians.com/bbq-pulled-chicken/",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 250,
        "prep_minutes": 10,
        "cook_minutes": 240,
        "cuisines": ["american"],
        "diet_tags": [],
        "dish_types": ["main course"],
        "equipment": ["slow_cooker"],
        "proteins": ["chicken"],
        "carbs": ["bread"],
        "ingredients": [
            {"name": "boneless skinless chicken breasts", "amount": 2, "unit": "lb", "aisle": "Meat",
             "group": "Chicken", "original_text": "2 lb boneless skinless chicken breasts"},
            {"name": "bbq sauce", "amount": 1.5, "unit": "cup", "aisle": "Condiments",
             "group": "Chicken", "original_text": "1.5 cups store-bought BBQ sauce, divided"},
            {"name": "apple cider vinegar", "amount": 2, "unit": "tbsp", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "Chicken", "original_text": "2 tbsp cider vinegar (brightens bottled sauce)"},
            {"name": "brown sugar", "amount": 1, "unit": "tbsp", "aisle": "Baking",
             "group": "Chicken", "original_text": "1 tbsp brown sugar"},
            {"name": "garlic powder", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Chicken", "original_text": "1 tsp garlic powder + 1 tsp onion powder"},
            {"name": "brioche buns", "amount": 4, "unit": "count", "aisle": "Bakery",
             "group": "Sandwiches", "original_text": "4 brioche or potato buns"},
            {"name": "coleslaw mix", "amount": 3, "unit": "cup", "aisle": "Produce",
             "group": "Sandwiches", "original_text": "3 cups slaw mix"},
            {"name": "coleslaw dressing", "amount": 0.33, "unit": "cup", "aisle": "Condiments",
             "group": "Sandwiches", "original_text": "1/3 cup coleslaw dressing"},
            {"name": "dill pickle chips", "amount": 0.5, "unit": "cup", "aisle": "Condiments",
             "group": "Sandwiches", "original_text": "dill pickle chips, for topping"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Put the chicken breasts in the slow cooker with 1 cup BBQ sauce, 2 tbsp vinegar, 1 tbsp brown sugar, garlic and onion powder. Toss to coat."},
            {"step_number": 2, "text": "Cook on LOW 4-5 hours (or HIGH 2.5-3) until the chicken shreds with no resistance and reads 165°F+."},
            {"step_number": 3, "text": "Shred the chicken right in the cooker with two forks."},
            {"step_number": 4, "text": "Stir in the remaining 1/2 cup BBQ sauce. If it looks wet, leave the lid off 10 minutes to thicken — sandwich filling, not soup."},
            {"step_number": 5, "text": "Quick slaw: toss the slaw mix with the dressing."},
            {"step_number": 6, "text": "Pile chicken on toasted buns, top with slaw and pickles. Leftover chicken freezes well for a fast second dinner."},
        ],
    },
    {
        "id": "gen_crispy_chicken_tenders",
        "title": "Crispy Oven Chicken Tenders",
        "source": "claude_chat",
        "source_url": "https://www.recipetineats.com/truly-golden-crunchy-baked-chicken-tenders-less-mess/",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 35,
        "prep_minutes": 15,
        "cook_minutes": 20,
        "cuisines": ["american"],
        "diet_tags": [],
        "dish_types": ["main course"],
        "equipment": ["oven", "air_fryer"],
        "proteins": ["chicken"],
        "carbs": ["potato"],
        "ingredients": [
            {"name": "chicken tenderloins", "amount": 1.75, "unit": "lb", "aisle": "Meat",
             "group": "Tenders", "original_text": "1.75 lb chicken tenderloins (or breasts cut into strips)"},
            {"name": "panko breadcrumbs", "amount": 2, "unit": "cup", "aisle": "Pantry",
             "group": "Tenders", "original_text": "2 cups panko (toast it first — the crunch trick)"},
            {"name": "all-purpose flour", "amount": 0.5, "unit": "cup", "aisle": "Baking",
             "group": "Tenders", "original_text": "1/2 cup flour"},
            {"name": "eggs", "amount": 2, "unit": "count", "aisle": "Eggs",
             "group": "Tenders", "original_text": "2 eggs, beaten"},
            {"name": "garlic powder", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Tenders", "original_text": "1 tsp garlic powder + 1 tsp paprika"},
            {"name": "kosher salt", "amount": 1.25, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Tenders", "original_text": "1.25 tsp kosher salt + black pepper"},
            {"name": "olive oil", "amount": 3, "unit": "tbsp", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "Tenders", "original_text": "3 tbsp olive oil (for toasting the panko)"},
            {"name": "frozen french fries", "amount": 1.5, "unit": "lb", "aisle": "Frozen",
             "group": "For serving", "original_text": "1.5 lb frozen fries (bake alongside)"},
            {"name": "honey mustard", "amount": 0.5, "unit": "cup", "aisle": "Condiments",
             "group": "For serving", "original_text": "honey mustard or ranch, for dipping"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Heat the oven to 425°F. Toast the panko: stir it with 3 tbsp oil in a dry skillet over medium 3-4 minutes until golden. This is the difference between crunchy and pale baked tenders."},
            {"step_number": 2, "text": "Set up three bowls: flour with garlic powder, paprika, 1.25 tsp salt and pepper; beaten eggs; toasted panko."},
            {"step_number": 3, "text": "Dredge each tender: flour, then egg, then press into the panko to coat all over."},
            {"step_number": 4, "text": "Line up on a rack-lined sheet pan (or air-fryer basket). Start the fries on a second pan."},
            {"step_number": 5, "text": "Bake 18-20 minutes (air fryer: 400°F, 10-12 min) until the chicken reads 165°F and the crust is deep golden — no flipping needed thanks to the pre-toast."},
            {"step_number": 6, "text": "Rest 3 minutes. Serve with fries and honey mustard or ranch."},
        ],
    },
    {
        "id": "gen_beef_philly_cheesesteak",
        "title": "Beef Philly Cheesesteak Skillet Subs",
        "source": "claude_chat",
        "source_url": "",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 30,
        "prep_minutes": 15,
        "cook_minutes": 15,
        "cuisines": ["american"],
        "diet_tags": [],
        "dish_types": ["main course"],
        "equipment": ["skillet", "stovetop"],
        "proteins": ["beef"],
        "carbs": ["bread"],
        "ingredients": [
            {"name": "ribeye steak", "amount": 1.5, "unit": "lb", "aisle": "Meat",
             "group": "Cheesesteak", "original_text": "1.5 lb ribeye or sirloin, sliced paper-thin (freeze 30 min first for easy slicing)"},
            {"name": "yellow onion", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Cheesesteak", "original_text": "1 large yellow onion, thinly sliced"},
            {"name": "green bell pepper", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Cheesesteak", "original_text": "1 green bell pepper, thin strips"},
            {"name": "provolone cheese", "amount": 8, "unit": "count", "aisle": "Cheese",
             "group": "Cheesesteak", "original_text": "8 slices provolone"},
            {"name": "worcestershire sauce", "amount": 1, "unit": "tbsp", "aisle": "Condiments",
             "group": "Cheesesteak", "original_text": "1 tbsp Worcestershire sauce"},
            {"name": "vegetable oil", "amount": 2, "unit": "tbsp", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "Cheesesteak", "original_text": "2 tbsp vegetable oil, divided"},
            {"name": "kosher salt", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Cheesesteak", "original_text": "1 tsp kosher salt + black pepper"},
            {"name": "hoagie rolls", "amount": 4, "unit": "count", "aisle": "Bakery",
             "group": "Subs", "original_text": "4 hoagie rolls, split and toasted"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Heat 1 tbsp oil in a large skillet over medium. Cook the onion and pepper 7-8 minutes until soft and lightly caramelized; remove to a plate."},
            {"step_number": 2, "text": "Crank the heat to high, add the last 1 tbsp oil. Add the thin-sliced beef in a single layer; don't stir for 60 seconds to get a sear."},
            {"step_number": 3, "text": "Stir-fry 2-3 minutes more until just cooked, then add 1 tbsp Worcestershire, 1 tsp salt, pepper. Thin beef cooks fast — pull it the moment it loses its pink."},
            {"step_number": 4, "text": "Return the onions and peppers; toss together and lower the heat."},
            {"step_number": 5, "text": "Divide into 4 piles in the pan, lay 2 provolone slices over each, cover 1 minute until melted and draped."},
            {"step_number": 6, "text": "Scoop each cheesy pile into a toasted hoagie roll."},
        ],
    },
    {
        "id": "gen_grilled_chicken_foil_packets",
        "title": "Grilled Chicken & Summer Veggie Foil Packets",
        "source": "claude_chat",
        "source_url": "https://www.twopeasandtheirpod.com/grilled-sausage-vegetable-foil-packets/",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 45,
        "prep_minutes": 15,
        "cook_minutes": 30,
        "cuisines": ["american"],
        "diet_tags": ["gluten free"],
        "dish_types": ["main course"],
        "equipment": ["grill"],
        "proteins": ["chicken"],
        "carbs": ["potato"],
        "ingredients": [
            {"name": "boneless skinless chicken thighs", "amount": 1.5, "unit": "lb", "aisle": "Meat",
             "group": "Packets", "original_text": "1.5 lb boneless skinless chicken thighs, 1-inch pieces"},
            {"name": "baby potatoes", "amount": 1, "unit": "lb", "aisle": "Produce",
             "group": "Packets", "original_text": "1 lb baby potatoes, quartered small"},
            {"name": "corn", "amount": 2, "unit": "count", "aisle": "Produce",
             "group": "Packets", "original_text": "2 ears corn, cut into rounds (or 1.5 cups frozen)"},
            {"name": "zucchini", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Packets", "original_text": "1 zucchini, thick half-moons"},
            {"name": "red bell pepper", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Packets", "original_text": "1 red bell pepper, chunks"},
            {"name": "olive oil", "amount": 3, "unit": "tbsp", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "Seasoning", "original_text": "3 tbsp olive oil"},
            {"name": "garlic", "amount": 3, "unit": "count", "aisle": "Produce",
             "group": "Seasoning", "original_text": "3 garlic cloves, minced"},
            {"name": "italian seasoning", "amount": 2, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Seasoning", "original_text": "2 tsp Italian seasoning"},
            {"name": "smoked paprika", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Seasoning", "original_text": "1 tsp smoked paprika"},
            {"name": "kosher salt", "amount": 1.25, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Seasoning", "original_text": "1.25 tsp kosher salt + black pepper"},
            {"name": "lemon", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "For serving", "original_text": "1 lemon, in wedges"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Heat the grill to medium-high (about 400°F). Microwave the potatoes with 2 tbsp water, covered, 4 minutes — they take longest, so give them a head start."},
            {"step_number": 2, "text": "Toss the chicken, potatoes, corn, zucchini, and pepper with 3 tbsp oil, garlic, 2 tsp Italian seasoning, 1 tsp paprika, 1.25 tsp salt, and pepper."},
            {"step_number": 3, "text": "Tear 4 large sheets of heavy-duty foil. Divide the mixture among them and fold into sealed packets, leaving a little air space and a small steam vent."},
            {"step_number": 4, "text": "Grill 18-22 minutes, flipping once, until the chicken reads 175°F and the potatoes are tender. (Oven: 425°F, 30 minutes, no flip.)"},
            {"step_number": 5, "text": "Open carefully — the steam is hot. Check a thick piece of chicken before serving."},
            {"step_number": 6, "text": "Finish with a squeeze of lemon. Eat straight from the foil — the whole point of a summer cookout dinner."},
        ],
    },
    # ---------------- ITALIAN ----------------
    {
        "id": "gen_baked_ziti",
        "title": "Baked Ziti",
        "source": "claude_chat",
        "source_url": "https://www.budgetbytes.com/classic-baked-ziti/",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 55,
        "prep_minutes": 15,
        "cook_minutes": 40,
        "cuisines": ["italian"],
        "diet_tags": [],
        "dish_types": ["main course"],
        "equipment": ["oven", "stovetop"],
        "proteins": ["beef"],
        "carbs": ["pasta"],
        "ingredients": [
            {"name": "ziti", "amount": 12, "unit": "oz", "aisle": "Pasta and Rice",
             "group": "Pasta", "original_text": "12 oz ziti or penne"},
            {"name": "ground beef", "amount": 1, "unit": "lb", "aisle": "Meat",
             "group": "Sauce", "original_text": "1 lb ground beef"},
            {"name": "marinara sauce", "amount": 24, "unit": "oz", "aisle": "Canned and Jarred",
             "group": "Sauce", "original_text": "1 jar (24 oz) marinara (don't make it — the house rule)"},
            {"name": "yellow onion", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Sauce", "original_text": "1 onion, chopped"},
            {"name": "garlic", "amount": 3, "unit": "count", "aisle": "Produce",
             "group": "Sauce", "original_text": "3 garlic cloves, minced"},
            {"name": "italian seasoning", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Sauce", "original_text": "1 tsp Italian seasoning"},
            {"name": "ricotta cheese", "amount": 15, "unit": "oz", "aisle": "Cheese",
             "group": "Cheese layer", "original_text": "1 tub (15 oz) ricotta"},
            {"name": "egg", "amount": 1, "unit": "count", "aisle": "Eggs",
             "group": "Cheese layer", "original_text": "1 egg (binds the ricotta)"},
            {"name": "shredded mozzarella", "amount": 2, "unit": "cup", "aisle": "Cheese",
             "group": "Cheese layer", "original_text": "2 cups shredded mozzarella, divided"},
            {"name": "parmesan cheese", "amount": 0.5, "unit": "cup", "aisle": "Cheese",
             "group": "Cheese layer", "original_text": "1/2 cup grated parmesan"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Heat the oven to 375°F. Boil the ziti 2 minutes short of al dente (it finishes in the oven); drain."},
            {"step_number": 2, "text": "Brown the beef with the onion in a skillet over medium-high, 6-7 minutes; add garlic and 1 tsp Italian seasoning, 1 minute. Spoon off fat, stir in the marinara, simmer 5 minutes."},
            {"step_number": 3, "text": "Mix the ricotta with the egg, parmesan, and 1/2 cup of the mozzarella."},
            {"step_number": 4, "text": "Fold the drained pasta into the meat sauce."},
            {"step_number": 5, "text": "Layer in a 9x13 dish: half the pasta, dollops of all the ricotta mixture, the rest of the pasta, then the remaining 1.5 cups mozzarella on top."},
            {"step_number": 6, "text": "Bake 25-30 minutes until bubbling at the edges and the cheese is golden. Broil 2 minutes if you want browner."},
            {"step_number": 7, "text": "Rest 10 minutes before scooping so it sets. Freezes well."},
        ],
    },
    {
        "id": "gen_chicken_parmesan",
        "title": "Chicken Parmesan",
        "source": "claude_chat",
        "source_url": "",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 45,
        "prep_minutes": 20,
        "cook_minutes": 25,
        "cuisines": ["italian"],
        "diet_tags": [],
        "dish_types": ["main course"],
        "equipment": ["oven", "skillet", "air_fryer"],
        "proteins": ["chicken"],
        "carbs": ["pasta"],
        "ingredients": [
            {"name": "boneless skinless chicken breasts", "amount": 2, "unit": "count", "aisle": "Meat",
             "group": "Cutlets", "original_text": "2 large chicken breasts, halved horizontally into 4 thin cutlets"},
            {"name": "panko breadcrumbs", "amount": 1.5, "unit": "cup", "aisle": "Pantry",
             "group": "Cutlets", "original_text": "1.5 cups panko"},
            {"name": "parmesan cheese", "amount": 0.5, "unit": "cup", "aisle": "Cheese",
             "group": "Cutlets", "original_text": "1/2 cup grated parmesan (in the breading)"},
            {"name": "all-purpose flour", "amount": 0.5, "unit": "cup", "aisle": "Baking",
             "group": "Cutlets", "original_text": "1/2 cup flour"},
            {"name": "eggs", "amount": 2, "unit": "count", "aisle": "Eggs",
             "group": "Cutlets", "original_text": "2 eggs, beaten"},
            {"name": "italian seasoning", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Cutlets", "original_text": "1 tsp Italian seasoning"},
            {"name": "kosher salt", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Cutlets", "original_text": "1 tsp kosher salt + black pepper"},
            {"name": "olive oil", "amount": 3, "unit": "tbsp", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "Cutlets", "original_text": "3 tbsp olive oil"},
            {"name": "marinara sauce", "amount": 2, "unit": "cup", "aisle": "Canned and Jarred",
             "group": "Topping", "original_text": "2 cups store-bought marinara"},
            {"name": "fresh mozzarella", "amount": 8, "unit": "oz", "aisle": "Cheese",
             "group": "Topping", "original_text": "8 oz fresh mozzarella, sliced"},
            {"name": "spaghetti", "amount": 12, "unit": "oz", "aisle": "Pasta and Rice",
             "group": "For serving", "original_text": "12 oz spaghetti"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Heat the oven to 425°F. Set up dredging: flour with 1 tsp salt and pepper; beaten eggs; panko mixed with the parmesan and 1 tsp Italian seasoning."},
            {"step_number": 2, "text": "Coat each cutlet: flour, egg, then press firmly into the panko-parm."},
            {"step_number": 3, "text": "Brown the cutlets in 3 tbsp oil in an oven-safe skillet over medium-high, 2-3 minutes per side, until golden (they won't be cooked through yet). Or air-fry at 400°F 10 minutes, no pan-frying."},
            {"step_number": 4, "text": "Start the spaghetti in salted boiling water."},
            {"step_number": 5, "text": "Spoon marinara over each cutlet, top with mozzarella slices."},
            {"step_number": 6, "text": "Bake 12-15 minutes until the chicken reads 165°F and the cheese is melted and blistered."},
            {"step_number": 7, "text": "Serve over spaghetti tossed with the extra warm marinara."},
        ],
    },
    {
        "id": "gen_italian_wedding_soup",
        "title": "Italian Wedding Soup (Turkey Meatballs)",
        "source": "claude_chat",
        "source_url": "https://www.budgetbytes.com/italian-wedding-soup/",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 45,
        "prep_minutes": 20,
        "cook_minutes": 25,
        "cuisines": ["italian"],
        "diet_tags": [],
        "dish_types": ["main course", "soup"],
        "equipment": ["dutch_oven", "stovetop"],
        "proteins": ["turkey"],
        "carbs": ["pasta"],
        "ingredients": [
            {"name": "ground turkey", "amount": 1, "unit": "lb", "aisle": "Meat",
             "group": "Meatballs", "original_text": "1 lb ground turkey"},
            {"name": "panko breadcrumbs", "amount": 0.5, "unit": "cup", "aisle": "Pantry",
             "group": "Meatballs", "original_text": "1/2 cup panko"},
            {"name": "egg", "amount": 1, "unit": "count", "aisle": "Eggs",
             "group": "Meatballs", "original_text": "1 egg"},
            {"name": "parmesan cheese", "amount": 0.5, "unit": "cup", "aisle": "Cheese",
             "group": "Meatballs", "original_text": "1/2 cup grated parmesan, divided"},
            {"name": "garlic", "amount": 3, "unit": "count", "aisle": "Produce",
             "group": "Meatballs", "original_text": "3 garlic cloves, minced, divided"},
            {"name": "italian seasoning", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Meatballs", "original_text": "1 tsp Italian seasoning"},
            {"name": "yellow onion", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Soup", "original_text": "1 onion, finely chopped"},
            {"name": "carrots", "amount": 2, "unit": "count", "aisle": "Produce",
             "group": "Soup", "original_text": "2 carrots, diced"},
            {"name": "celery", "amount": 2, "unit": "count", "aisle": "Produce",
             "group": "Soup", "original_text": "2 celery stalks, diced"},
            {"name": "chicken broth", "amount": 8, "unit": "cup", "aisle": "Canned and Jarred",
             "group": "Soup", "original_text": "8 cups chicken broth"},
            {"name": "acini di pepe pasta", "amount": 0.75, "unit": "cup", "aisle": "Pasta and Rice",
             "group": "Soup", "original_text": "3/4 cup acini di pepe or orzo"},
            {"name": "baby spinach", "amount": 4, "unit": "cup", "aisle": "Produce",
             "group": "Soup", "original_text": "4 cups baby spinach"},
            {"name": "olive oil", "amount": 2, "unit": "tbsp", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "Soup", "original_text": "2 tbsp olive oil"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Mix the meatballs: turkey, panko, egg, 1/4 cup parmesan, 1 garlic clove, 1 tsp Italian seasoning, 3/4 tsp salt. Roll into ~30 small (1-inch) meatballs — small ones are the signature."},
            {"step_number": 2, "text": "Heat 2 tbsp oil in a dutch oven over medium. Cook the onion, carrots, and celery 6 minutes; add the remaining garlic, 1 minute."},
            {"step_number": 3, "text": "Add 8 cups broth and bring to a gentle simmer."},
            {"step_number": 4, "text": "Drop the meatballs in straight (no pre-browning needed); simmer 10 minutes until they float and read 165°F."},
            {"step_number": 5, "text": "Add the acini di pepe; cook 8 minutes until tender."},
            {"step_number": 6, "text": "Stir in the spinach until wilted, 1 minute. Season with salt and pepper."},
            {"step_number": 7, "text": "Serve with the remaining parmesan over the top. The pasta drinks broth — leftovers need a splash more."},
        ],
    },
    {
        "id": "gen_tuscan_white_bean_sausage",
        "title": "Tuscan White Bean & Sausage Skillet",
        "source": "claude_chat",
        "source_url": "https://www.budgetbytes.com/italian-sausage-white-bean-skillet/",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 30,
        "prep_minutes": 10,
        "cook_minutes": 20,
        "cuisines": ["italian"],
        "diet_tags": [],
        "dish_types": ["main course"],
        "equipment": ["skillet", "stovetop"],
        "proteins": ["pork"],
        "carbs": ["bread"],
        "ingredients": [
            {"name": "italian sausage", "amount": 1, "unit": "lb", "aisle": "Meat",
             "group": "Skillet", "original_text": "1 lb sweet (mild) Italian sausage, casings removed"},
            {"name": "cannellini beans", "amount": 30, "unit": "oz", "aisle": "Canned and Jarred",
             "group": "Skillet", "original_text": "2 cans (15 oz each) cannellini beans, drained and rinsed"},
            {"name": "diced tomatoes", "amount": 14.5, "unit": "oz", "aisle": "Canned and Jarred",
             "group": "Skillet", "original_text": "1 can (14.5 oz) diced tomatoes"},
            {"name": "yellow onion", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "Skillet", "original_text": "1 onion, chopped"},
            {"name": "garlic", "amount": 4, "unit": "count", "aisle": "Produce",
             "group": "Skillet", "original_text": "4 garlic cloves, minced"},
            {"name": "chicken broth", "amount": 0.75, "unit": "cup", "aisle": "Canned and Jarred",
             "group": "Skillet", "original_text": "3/4 cup chicken broth"},
            {"name": "baby kale", "amount": 4, "unit": "cup", "aisle": "Produce",
             "group": "Skillet", "original_text": "4 cups baby kale or spinach"},
            {"name": "italian seasoning", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Skillet", "original_text": "1 tsp Italian seasoning"},
            {"name": "olive oil", "amount": 1, "unit": "tbsp", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "Skillet", "original_text": "1 tbsp olive oil"},
            {"name": "parmesan cheese", "amount": 0.5, "unit": "cup", "aisle": "Cheese",
             "group": "For serving", "original_text": "1/2 cup grated parmesan"},
            {"name": "crusty bread", "amount": 1, "unit": "count", "aisle": "Bakery",
             "group": "For serving", "original_text": "1 crusty loaf, for mopping"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Heat 1 tbsp oil in a large skillet over medium-high. Cook the sausage, breaking it up, 5-6 minutes until browned and crispy in spots."},
            {"step_number": 2, "text": "Add the onion; cook 4 minutes until soft. Add garlic and 1 tsp Italian seasoning, 1 minute."},
            {"step_number": 3, "text": "Add the beans, tomatoes, and 3/4 cup broth. Simmer 8 minutes."},
            {"step_number": 4, "text": "Mash about a third of the beans against the pan to thicken into a creamy, stew-like base."},
            {"step_number": 5, "text": "Stir in the kale until wilted, 2 minutes. Season with salt and pepper."},
            {"step_number": 6, "text": "Top with parmesan and serve with crusty bread for scooping. One pan, 30 minutes."},
        ],
    },
    # ---------------- FISH ----------------
    {
        "id": "gen_air_fryer_fish_chips",
        "title": "Air-Fryer Fish & Chips",
        "source": "claude_chat",
        "source_url": "",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 40,
        "prep_minutes": 15,
        "cook_minutes": 25,
        "cuisines": ["american"],
        "diet_tags": [],
        "dish_types": ["main course"],
        "equipment": ["air_fryer"],
        "proteins": ["fish"],
        "carbs": ["potato"],
        "ingredients": [
            {"name": "cod fillets", "amount": 1.5, "unit": "lb", "aisle": "Seafood",
             "group": "Fish", "original_text": "1.5 lb cod fillets, cut into 4 portions, patted very dry"},
            {"name": "panko breadcrumbs", "amount": 1.5, "unit": "cup", "aisle": "Pantry",
             "group": "Fish", "original_text": "1.5 cups panko"},
            {"name": "all-purpose flour", "amount": 0.5, "unit": "cup", "aisle": "Baking",
             "group": "Fish", "original_text": "1/2 cup flour"},
            {"name": "eggs", "amount": 2, "unit": "count", "aisle": "Eggs",
             "group": "Fish", "original_text": "2 eggs, beaten"},
            {"name": "old bay seasoning", "amount": 1, "unit": "tbsp", "aisle": "Spices and Seasonings",
             "group": "Fish", "original_text": "1 tbsp Old Bay (or paprika + garlic powder)"},
            {"name": "olive oil", "amount": 3, "unit": "tbsp", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "Fish", "original_text": "3 tbsp olive oil (toast the panko)"},
            {"name": "russet potatoes", "amount": 1.5, "unit": "lb", "aisle": "Produce",
             "group": "Chips", "original_text": "1.5 lb russet potatoes, cut into wedges"},
            {"name": "tartar sauce", "amount": 0.5, "unit": "cup", "aisle": "Condiments",
             "group": "For serving", "original_text": "tartar sauce + lemon wedges"},
            {"name": "lemon", "amount": 1, "unit": "count", "aisle": "Produce",
             "group": "For serving", "original_text": "1 lemon, in wedges"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Toss the potato wedges with 1 tbsp oil and salt; air-fry at 400°F for 18-20 minutes, shaking twice, until crisp. Hold warm while the fish cooks."},
            {"step_number": 2, "text": "Toast the panko with 2 tbsp oil in a dry skillet, 3-4 minutes until golden — this gives air-fried fish a real fried crunch."},
            {"step_number": 3, "text": "Set up: flour with 1 tbsp Old Bay; beaten eggs; toasted panko. Pat the cod bone-dry first or the coating slides off."},
            {"step_number": 4, "text": "Dredge each piece: flour, egg, panko, pressing to coat."},
            {"step_number": 5, "text": "Air-fry the fish at 400°F for 9-11 minutes (no flip) until the coating is deep golden and the fish flakes at 145°F."},
            {"step_number": 6, "text": "Serve right away with the chips, tartar sauce, and lemon."},
        ],
    },
    {
        "id": "gen_baja_fish_tacos",
        "title": "Baja Fish Tacos",
        "source": "claude_chat",
        "source_url": "https://www.simplyscratch.com/air-fryer-baja-fish-tacos/",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 35,
        "prep_minutes": 15,
        "cook_minutes": 15,
        "cuisines": ["mexican"],
        "diet_tags": [],
        "dish_types": ["main course"],
        "equipment": ["air_fryer"],
        "proteins": ["fish"],
        "carbs": ["bread"],
        "ingredients": [
            {"name": "cod fillets", "amount": 1.25, "unit": "lb", "aisle": "Seafood",
             "group": "Fish", "original_text": "1.25 lb cod or tilapia, cut into strips, patted dry"},
            {"name": "panko breadcrumbs", "amount": 1.25, "unit": "cup", "aisle": "Pantry",
             "group": "Fish", "original_text": "1.25 cups panko"},
            {"name": "all-purpose flour", "amount": 0.33, "unit": "cup", "aisle": "Baking",
             "group": "Fish", "original_text": "1/3 cup flour"},
            {"name": "eggs", "amount": 2, "unit": "count", "aisle": "Eggs",
             "group": "Fish", "original_text": "2 eggs, beaten"},
            {"name": "chili powder", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Fish", "original_text": "1 tsp mild chili powder + 1 tsp cumin"},
            {"name": "olive oil", "amount": 2, "unit": "tbsp", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "Fish", "original_text": "2 tbsp olive oil (toast the panko)"},
            {"name": "mayonnaise", "amount": 0.5, "unit": "cup", "aisle": "Condiments",
             "group": "Crema", "original_text": "1/2 cup mayonnaise"},
            {"name": "lime", "amount": 2, "unit": "count", "aisle": "Produce",
             "group": "Crema", "original_text": "2 limes (1 juiced into the crema, 1 in wedges)"},
            {"name": "corn tortillas", "amount": 8, "unit": "count", "aisle": "Bakery",
             "group": "Tacos", "original_text": "8 corn tortillas, warmed"},
            {"name": "shredded cabbage", "amount": 3, "unit": "cup", "aisle": "Produce",
             "group": "Tacos", "original_text": "3 cups shredded cabbage or slaw mix"},
            {"name": "fresh cilantro", "amount": 0.25, "unit": "cup", "aisle": "Produce",
             "group": "Tacos", "original_text": "1/4 cup cilantro"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Lime crema: stir mayo with the juice of 1 lime and a pinch of salt. Thin with a splash of water to drizzle. Refrigerate."},
            {"step_number": 2, "text": "Toast the panko with 2 tbsp oil in a dry skillet, 3-4 minutes until golden."},
            {"step_number": 3, "text": "Set up: flour with 1 tsp chili powder and 1 tsp cumin; beaten eggs; toasted panko. Pat the fish strips very dry."},
            {"step_number": 4, "text": "Dredge each strip: flour, egg, panko."},
            {"step_number": 5, "text": "Air-fry at 400°F for 8-10 minutes until golden and the fish flakes at 145°F."},
            {"step_number": 6, "text": "Build tacos on warm tortillas: cabbage, fish, drizzle of crema, cilantro, lime. (Doubles as your fish-or-Mexican night.)"},
        ],
    },
    {
        "id": "gen_fish_sticks",
        "title": "Homemade Air-Fryer Fish Sticks",
        "source": "claude_chat",
        "source_url": "",
        "image_url": "",
        "servings_original": 4,
        "ready_in_minutes": 30,
        "prep_minutes": 15,
        "cook_minutes": 15,
        "cuisines": ["american"],
        "diet_tags": [],
        "dish_types": ["main course"],
        "equipment": ["air_fryer"],
        "proteins": ["fish"],
        "carbs": ["potato"],
        "ingredients": [
            {"name": "cod fillets", "amount": 1.5, "unit": "lb", "aisle": "Seafood",
             "group": "Fish sticks", "original_text": "1.5 lb cod, cut into 3/4-inch-wide sticks, patted dry"},
            {"name": "panko breadcrumbs", "amount": 1.5, "unit": "cup", "aisle": "Pantry",
             "group": "Fish sticks", "original_text": "1.5 cups panko"},
            {"name": "all-purpose flour", "amount": 0.5, "unit": "cup", "aisle": "Baking",
             "group": "Fish sticks", "original_text": "1/2 cup flour"},
            {"name": "eggs", "amount": 2, "unit": "count", "aisle": "Eggs",
             "group": "Fish sticks", "original_text": "2 eggs, beaten"},
            {"name": "garlic powder", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Fish sticks", "original_text": "1 tsp garlic powder + 1 tsp paprika"},
            {"name": "kosher salt", "amount": 1, "unit": "tsp", "aisle": "Spices and Seasonings",
             "group": "Fish sticks", "original_text": "1 tsp kosher salt"},
            {"name": "olive oil", "amount": 2, "unit": "tbsp", "aisle": "Oil, Vinegar, Salad Dressing",
             "group": "Fish sticks", "original_text": "2 tbsp olive oil (toast the panko)"},
            {"name": "frozen french fries", "amount": 1.5, "unit": "lb", "aisle": "Frozen",
             "group": "For serving", "original_text": "1.5 lb frozen fries or tater tots"},
            {"name": "ketchup", "amount": 0.5, "unit": "cup", "aisle": "Condiments",
             "group": "For serving", "original_text": "ketchup and/or tartar sauce, for dipping"},
        ],
        "instructions": [
            {"step_number": 1, "text": "Air-fry the frozen fries at 400°F per the bag (about 15 minutes); hold warm while the fish cooks."},
            {"step_number": 2, "text": "Toast the panko with 2 tbsp oil in a dry skillet, 3-4 minutes until golden — the trick for crunchy air-fried coating."},
            {"step_number": 3, "text": "Set up: flour with garlic powder, paprika, 1 tsp salt; beaten eggs; toasted panko."},
            {"step_number": 4, "text": "Dredge each fish stick: flour, egg, panko, pressing to coat."},
            {"step_number": 5, "text": "Air-fry at 400°F for 8-10 minutes until golden and the fish flakes at 145°F. Work in a single layer — crowding steams them."},
            {"step_number": 6, "text": "Serve with the fries and ketchup or tartar. Way better than the freezer box; the kids won't go back."},
        ],
    },
]
